 'use client'

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'uz' | 'ru' | 'en'

type LanguageContextValue = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    // Sidebar
    'sidebar.dashboard': 'Bosh sahifa',
    'sidebar.steps': 'Qadamlar',
    'sidebar.gymFinder': 'Zallar',
    'sidebar.aiChat': 'AI Chat',
    'sidebar.recipes': 'Retseptlar',
    'sidebar.aiTrainer': 'AI Trener',
    'sidebar.insights': 'Tahlil va Statistika',
    'sidebar.goals': 'Maqsadlar',
    'sidebar.settings': 'Sozlamalar',

    // Settings
    'settings.title': 'Sozlamalar',
    'settings.language': 'Til',
    'settings.language.desc': "Ilova tilini o'zgartiring",
    'settings.notifications': 'Bildirishnomalar',
    'settings.notifications.desc': 'Eslatmalar va motivatsion xabarlar',
    'settings.motivational': 'Motivatsion bildirishnomalar',
    'settings.motivational.desc': "Nega kirmayapsan? Dietani to'xtatma!",
    'settings.mealReminders': 'Ovqat eslatmalari',
    'settings.breakfast': 'Nonushta',
    'settings.lunch': 'Tushlik',
    'settings.dinner': 'Kechki ovqat',
    'settings.waterReminders': 'Suv eslatmalari',
    'settings.waterReminders.desc': 'Kun davomida suv ichishni eslatma',
    'settings.goals': 'Maqsadlar va Salomatlik',
    'settings.goals.desc': 'Vazn va kaloriya maqsadlari',
    'settings.currentWeight': 'Joriy vazn (kg)',
    'settings.targetWeight': 'Maqsad vazn (kg)',
    'settings.calorieTarget': 'Kunlik kaloriya maqsadi',
    'settings.macroRatios': 'Makro nisbatlar',
    'settings.protein': 'Protein',
    'settings.carbs': 'Uglevodlar',
    'settings.fats': "Yog'lar",
    'settings.waterGoal': 'Kunlik suv maqsadi (litr)',
    'settings.appearance': "Tashqi ko'rinish",
    'settings.appearance.desc': 'Mavzu va ranglar',
    'settings.darkMode': "Qorong'i rejim",
    'settings.darkMode.desc': "Qorong'i mavzuni yoqish",
    'settings.account': "Hisob va Ma'lumotlar",
    'settings.account.desc': "Profil va ma'lumotlarni boshqarish",
    'settings.editProfile': 'Profilni tahrirlash',
    'settings.name': 'Ism',
    'settings.email': 'Email',
    'settings.save': 'Saqlash',
    'settings.resetProgress': 'Progressni tiklash',
    'settings.resetProgress.desc': "Barcha ma'lumotlarni o'chirish",
    'settings.logout': 'Chiqish',
    'settings.logout.desc': 'Hisobdan chiqish',
    'settings.confirmReset': 'Progressni tiklashni tasdiqlang',
    'settings.confirmReset.desc': "Bu amal barcha ma'lumotlarni o'chiradi va uni qaytarib bo'lmaydi.",
    'settings.confirm': 'Tasdiqlash',
    'settings.cancel': 'Bekor qilish',
    'settings.confirmLogout': 'Chiqishni tasdiqlang',
    'settings.confirmLogout.desc': 'Hisobingizdan chiqishni xohlaysizmi?',
    'settings.light': "Yorug'",
    'settings.dark': "Qorong'i",

    // AI Trainer Section
    'aiTrainer.badge': "Sun'iy intellekt Murabbiyi",
    'aiTrainer.title': "SI Murabbiy nazorati",
    'aiTrainer.subtitle': "Riyoatni monitoring qilish, seriyalar va odatlarni to'g'rilash.",
    'aiTrainer.days.mon': "Dush",
    'aiTrainer.days.tue': "Sesh",
    'aiTrainer.days.wed': "Chor",
    'aiTrainer.days.thu': "Pay",
    'aiTrainer.days.fri': "Jum",
    'aiTrainer.days.sat': "Shan",
    'aiTrainer.days.sun': "Yak",
    'aiTrainer.stats.weeklyScore': "Haftalik rioya qilish balim",
    'aiTrainer.stats.loggingStreak': "Yozib borish seriyasi (kun)",
    'aiTrainer.stats.activeWarnings': "Faol ogohlantirishlar",
    'aiTrainer.stats.dismissed': "yashirildi",
    'aiTrainer.stats.noDismissed': "Yashirilganlar yo'q",
    'aiTrainer.chart.title': "Haftalik rioya ko'rsatkichi",
    'aiTrainer.chart.subtitle': "Oziqlanish va faollik rejasiga kunlik amal qilish",
    'aiTrainer.warningsSection.title': "Ogohlantirish bildirishnomalari",
    'aiTrainer.warningsSection.subtitle': "O'tkazib yuborilgan qaydlar va diyetadan chetlashishlar",
    'aiTrainer.warnings.missedThu.title': "Payshanba kuni ovqatlanish qayd etilmadi",
    'aiTrainer.warnings.missedThu.detail': "Payshanba kuni uchun hech qanday ovqatlanish yozib borilmadi. Bu sizning haftalik statistikangiz xatoligiga olib kelishi mumkin.",
    'aiTrainer.warnings.missedThu.tip': "Xotiradan tiklash uchun o'tkazib yuborilgan ovqatlarni qo'shing.",
    'aiTrainer.warnings.overCarbs.title': "Uglevodlar me'yoridan oshdi",
    'aiTrainer.warnings.overCarbs.detail': "Kechki ovqatda mo'ljallangan uglevodlar miqdori 35g ga oshib ketdi.",
    'aiTrainer.warnings.overCarbs.tip': "Ertangi nonushta va tushlikda uglevodlarni biroz kamaytiring.",
    'aiTrainer.warnings.lowSteps.title': "Qadamlar soni kam",
    'aiTrainer.warnings.lowSteps.detail': "Kunlik qadamlar maqsadi 3,000 qadamga kam bajarildi.",
    'aiTrainer.warnings.lowSteps.tip': "Kechki payt 20 daqiqalik sayr qilishni rejalashtiring.",
    'aiTrainer.severity.high': "Yuqori",
    'aiTrainer.severity.medium': "O'rta",
    'aiTrainer.severity.low': "Past",
    'aiTrainer.habitCorrection': "Odatni to'g'rilash:",
    'aiTrainer.dismiss': "Yopish",
    'aiTrainer.allClear.title': "Barcha ogohlantirishlar hal qilindi",
    'aiTrainer.allClear.subtitle': "Siz ajoyib natija ko'rsatmoqdasiz! Shunday davom eting.",
    'aiTrainer.habitsSection.title': "Odatlar ro'yxati",
    'aiTrainer.habitsSection.subtitle': "Ushbu haftaning asosiy xatti-harakatlari",
    'aiTrainer.habits.loggedMeals': "Barcha ovqatlarni yozish",
    'aiTrainer.habits.hitProtein': "Oqsil me'yoriga etish",
    'aiTrainer.habits.calorieRange': "Kaloriya oralig'ida bo'lish",
    'aiTrainer.habits.completedSteps': "Qadamlar maqsadini bajarish",
    'aiTrainer.habits.drankWater': "Kunlik suvni ichish",
    'aiTrainer.recommendation.title': "Tavsiya",
    'aiTrainer.recommendation.text.before': "Oqsil iste'moli va suv balansi barqaror. Ketma-ketlikni saqlab qolish uchun ",
    'aiTrainer.recommendation.text.highlight': "kechki ovqatni vaqtida qayd etishga ",
    'aiTrainer.recommendation.text.after': "e'tibor bering.",

    // Goals Section
    'goals.title': 'Maqsadlar va Yutuqlar',
    'goals.subtitle': 'O‘z maqsadingizni belgilang, progressni kuzating va yutuqlarga erishing',
    'goals.addGoal': 'Yangi maqsad',
    'goals.activeGoals': 'Faol maqsadlar',
    'goals.completedGoals': 'Bajarilgan maqsadlar',
    'goals.progress': 'Progress',
    'goals.targetDate': 'Muddat',
    'goals.daysLeft': 'kun qoldi',
    'goals.completed': 'Bajarildi',
    'goals.category.weight': 'Vazn',
    'goals.category.fitness': 'Fitnes',
    'goals.category.nutrition': 'Oziqlanish',
    'goals.category.habit': 'Odat',
    'goals.newGoalModal.title': 'Yangi maqsad qo‘shish',
    'goals.newGoalModal.goalTitle': 'Maqsad nomi',
    'goals.newGoalModal.category': 'Kategoriya',
    'goals.newGoalModal.targetValue': 'Maqsad ko‘rsatkichi',
    'goals.newGoalModal.currentValue': 'Joriy ko‘rsatkich',
    'goals.newGoalModal.unit': 'O‘lchov birligi (kg, kun, va h.k.)',
    'goals.newGoalModal.deadline': 'Oxirgi muddat',
    'goals.newGoalModal.save': 'Saqlash',
    'goals.newGoalModal.cancel': 'Bekor qilish',

    // Gym Finder Section
  'gymFinder.badge': 'Toshkent',
  'gymFinder.title': 'Sport Zallari va Trenerlar',
  'gymFinder.subtitle': 'Toshkentdagi o‘zingizga yaqin sport zallari va shaxsiy murabbiylarni toping.',
  'gymFinder.searchPlaceholder': 'Zal nomi yoki tuman bo‘yicha qidiring...',
  'gymFinder.reviews': 'sharhlar',
  'gymFinder.facilities': 'Qulayliklar va Imkoniyatlar',
  'gymFinder.trainers': 'Shaxsiy murabbiylar',
  'gymFinder.notFound': 'bo‘yicha hech qanday zal topilmadi.',
  'gymFinder.facility.freeWeights': 'Erkin vaznlar',
  'gymFinder.facility.pool': 'Basseyn',
  'gymFinder.facility.cafe': 'Kafe',
  'gymFinder.facility.parking': 'Avtoturargoh',
  'gymFinder.facility.crossfit': 'CrossFit zonasi',
  'gymFinder.facility.wifi': 'Bepul Wi-Fi',
  'gymFinder.facility.sauna': 'Sauna',
  'gymFinder.specialty.strength': 'Kuch va chidamlilik',
  'gymFinder.specialty.yoga': 'Yoga va harakatchanlik',
  'gymFinder.specialty.crossfit': 'CrossFit va HIIT',
  'gymFinder.specialty.pilates': 'Pilates',
  'gymFinder.specialty.boxing': 'Boks',
  'gymFinder.specialty.bodybuilding': 'Bodibilding',
  'gymFinder.specialty.weightLoss': 'Ozg‘inlik va vazn tashlash',
  'gymFinder.specialty.functional': 'Funksional mashg‘ulotlar',
  'gymFinder.exp': 'yil',
  },
  ru: {
    // Sidebar
    'sidebar.dashboard': 'Главная',
    'sidebar.steps': 'Шаги',
    'sidebar.gymFinder': 'Залы',
    'sidebar.aiChat': 'AI Чат',
    'sidebar.recipes': 'Рецепты',
    'sidebar.aiTrainer': 'AI Тренер',
    'sidebar.insights': 'Аналитика',
    'sidebar.goals': 'Цели',
    'sidebar.settings': 'Настройки',

    // Settings
    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.language.desc': 'Изменить язык приложения',
    'settings.notifications': 'Уведомления',
    'settings.notifications.desc': 'Напоминания и мотивационные сообщения',
    'settings.motivational': 'Мотивационные уведомления',
    'settings.motivational.desc': 'Почему не заходишь? Не прерывай диету!',
    'settings.mealReminders': 'Напоминания о приёмах пищи',
    'settings.breakfast': 'Завтрак',
    'settings.lunch': 'Обед',
    'settings.dinner': 'Ужин',
    'settings.waterReminders': 'Напоминания о воде',
    'settings.waterReminders.desc': 'Напоминания пить воду в течение дня',
    'settings.goals': 'Цели и Здоровье',
    'settings.goals.desc': 'Цели по весу и калориям',
    'settings.currentWeight': 'Текущий вес (кг)',
    'settings.targetWeight': 'Целевой вес (кг)',
    'settings.calorieTarget': 'Дневная цель калорий',
    'settings.macroRatios': 'Соотношение макросов',
    'settings.protein': 'Белки',
    'settings.carbs': 'Углеводы',
    'settings.fats': 'Жиры',
    'settings.waterGoal': 'Дневная цель воды (литры)',
    'settings.appearance': 'Оформление',
    'settings.appearance.desc': 'Тема и цвета',
    'settings.darkMode': 'Тёмная тема',
    'settings.darkMode.desc': 'Включить тёмную тему',
    'settings.account': 'Аккаунт и Данные',
    'settings.account.desc': 'Управление профилем и данными',
    'settings.editProfile': 'Редактировать профиль',
    'settings.name': 'Имя',
    'settings.email': 'Эл. почта',
    'settings.save': 'Сохранить',
    'settings.resetProgress': 'Сбросить прогресс',
    'settings.resetProgress.desc': 'Удалить все данные',
    'settings.logout': 'Выйти',
    'settings.logout.desc': 'Выйти из аккаунта',
    'settings.confirmReset': 'Подтвердите сброс',
    'settings.confirmReset.desc': 'Это действие удалит все данные и не может быть отменено.',
    'settings.confirm': 'Подтвердить',
    'settings.cancel': 'Отмена',
    'settings.confirmLogout': 'Подтвердите выход',
    'settings.confirmLogout.desc': 'Вы действительно хотите выйти?',
    'settings.light': 'Светлая',
    'settings.dark': 'Тёмная',

    // AI Trainer Section
    'aiTrainer.badge': "ИИ Тренер",
    'aiTrainer.title': "Контроль ИИ Тренера",
    'aiTrainer.subtitle': "Мониторинг соблюдения, серии и исправление привычек.",
    'aiTrainer.days.mon': "Пн",
    'aiTrainer.days.tue': "Вт",
    'aiTrainer.days.wed': "Ср",
    'aiTrainer.days.thu': "Чт",
    'aiTrainer.days.fri': "Пт",
    'aiTrainer.days.sat': "Сб",
    'aiTrainer.days.sun': "Вс",
    'aiTrainer.stats.weeklyScore': "Еженедельный балл соблюдения",
    'aiTrainer.stats.loggingStreak': "Серия записей (дней)",
    'aiTrainer.stats.activeWarnings': "Активные предупреждения",
    'aiTrainer.stats.dismissed': "скрыто",
    'aiTrainer.stats.noDismissed': "Скрытых нет",
    'aiTrainer.chart.title': "Показатель еженедельного соблюдения",
    'aiTrainer.chart.subtitle': "Ежедневное следование плану питания и активности",
    'aiTrainer.warningsSection.title': "Уведомления и предупреждения",
    'aiTrainer.warningsSection.subtitle': "Пропущенные записи и отклонения от диеты",
    'aiTrainer.warnings.missedThu.title': "Питание в четверг не записано",
    'aiTrainer.warnings.missedThu.detail': "За четверг не было внесено ни одного приема пищи. Это может повлиять на точность еженедельной статистики.",
    'aiTrainer.warnings.missedThu.tip': "Добавьте пропущенные приемы пищи по памяти.",
    'aiTrainer.warnings.overCarbs.title': "Превышение нормы углеводов",
    'aiTrainer.warnings.overCarbs.detail': "Количество углеводов во время ужина превысило норму на 35г.",
    'aiTrainer.warnings.overCarbs.tip': "Немного сократите углеводы во время завтрака и обеда завтра.",
    'aiTrainer.warnings.lowSteps.title': "Низкая активность (шаги)",
    'aiTrainer.warnings.lowSteps.detail': "Дневная цель по шагам не дотянута на 3 000 шагов.",
    'aiTrainer.warnings.lowSteps.tip': "Запланируйте 20-минутную вечернюю прогулку.",
    'aiTrainer.severity.high': "Высокий",
    'aiTrainer.severity.medium': "Средний",
    'aiTrainer.severity.low': "Низкий",
    'aiTrainer.habitCorrection': "Коррекция привычки:",
    'aiTrainer.dismiss': "Закрыть",
    'aiTrainer.allClear.title': "Все предупреждения устранены",
    'aiTrainer.allClear.subtitle': "Отличный результат! Продолжайте в том же духе.",
    'aiTrainer.habitsSection.title': "Список привычек",
    'aiTrainer.habitsSection.subtitle': "Основные действия на этой неделе",
    'aiTrainer.habits.loggedMeals': "Записывать все приемы пищи",
    'aiTrainer.habits.hitProtein': "Выполнять норму белка",
    'aiTrainer.habits.calorieRange': "Оставаться в пределах калорий",
    'aiTrainer.habits.completedSteps': "Выполнить цель по шагам",
    'aiTrainer.habits.drankWater': "Выпивать дневную норму воды",
    'aiTrainer.recommendation.title': "Рекомендация",
    'aiTrainer.recommendation.text.before': "Потребление белка и водный баланс стабильны. Чтобы сохранить серию, ",
    'aiTrainer.recommendation.text.highlight': "уделите внимание своевременной записи ужина.",
    'aiTrainer.recommendation.text.after': "",

    // Goals Section
    'goals.title': 'Цели и Достижения',
    'goals.subtitle': 'Устанавливайте цели, отслеживайте прогресс и достигайте результатов',
    'goals.addGoal': 'Новая цель',
    'goals.activeGoals': 'Активные цели',
    'goals.completedGoals': 'Завершенные цели',
    'goals.progress': 'Прогресс',
    'goals.targetDate': 'Срок',
    'goals.daysLeft': 'дней осталось',
    'goals.completed': 'Завершено',
    'goals.category.weight': 'Вес',
    'goals.category.fitness': 'Фитнес',
    'goals.category.nutrition': 'Питание',
    'goals.category.habit': 'Привычка',
    'goals.newGoalModal.title': 'Добавить новую цель',
    'goals.newGoalModal.goalTitle': 'Название цели',
    'goals.newGoalModal.category': 'Категория',
    'goals.newGoalModal.targetValue': 'Целевой показатель',
    'goals.newGoalModal.currentValue': 'Текущий показатель',
    'goals.newGoalModal.unit': 'Единица измерения (кг, дней и т.д.)',
    'goals.newGoalModal.deadline': 'Крайний срок',
    'goals.newGoalModal.save': 'Сохранить',
    'goals.newGoalModal.cancel': 'Отмена',

    // Gym Finder Section
  'gymFinder.badge': 'Ташкент',
  'gymFinder.title': 'Спортзалы и Тренеры',
  'gymFinder.subtitle': 'Найдите ближайшие спортивные залы и персональных тренеров в Ташкенте.',
  'gymFinder.searchPlaceholder': 'Поиск по названию или району...',
  'gymFinder.reviews': 'отзывов',
  'gymFinder.facilities': 'Удобства и Оснащение',
  'gymFinder.trainers': 'Персональные тренеры',
  'gymFinder.notFound': 'по запросу ничего не найдено.',
  'gymFinder.facility.freeWeights': 'Свободные веса',
  'gymFinder.facility.pool': 'Бассейн',
  'gymFinder.facility.cafe': 'Кафе',
  'gymFinder.facility.parking': 'Парковка',
  'gymFinder.facility.crossfit': 'Кроссфит зона',
  'gymFinder.facility.wifi': 'Бесплатный Wi-Fi',
  'gymFinder.facility.sauna': 'Сауна',
  'gymFinder.specialty.strength': 'Силовой тренинг',
  'gymFinder.specialty.yoga': 'Йога и гибкость',
  'gymFinder.specialty.crossfit': 'CrossFit и HIIT',
  'gymFinder.specialty.pilates': 'Пилатес',
  'gymFinder.specialty.boxing': 'Бокс',
  'gymFinder.specialty.bodybuilding': 'Бодибилдинг',
  'gymFinder.specialty.weightLoss': 'Похудение',
  'gymFinder.specialty.functional': 'Функциональный тренинг',
  'gymFinder.exp': 'лет',
  },
  en: {
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.steps': 'Steps',
    'sidebar.gymFinder': 'Gym Finder',
    'sidebar.aiChat': 'AI Chat',
    'sidebar.recipes': 'Recipes',
    'sidebar.aiTrainer': 'AI Trainer',
    'sidebar.insights': 'Insights',
    'sidebar.goals': 'Goals',
    'sidebar.settings': 'Settings',

    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.desc': 'Change the app language',
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Reminders and motivational messages',
    'settings.motivational': 'Motivational Notifications',
    'settings.motivational.desc': "Why haven't you logged in today? Don't break your diet streak!",
    'settings.mealReminders': 'Meal Reminders',
    'settings.breakfast': 'Breakfast',
    'settings.lunch': 'Lunch',
    'settings.dinner': 'Dinner',
    'settings.waterReminders': 'Water Reminders',
    'settings.waterReminders.desc': 'Stay hydrated with water tracking reminders',
    'settings.goals': 'Goals & Health Profile',
    'settings.goals.desc': 'Weight and calorie targets',
    'settings.currentWeight': 'Current Weight (kg)',
    'settings.targetWeight': 'Target Weight (kg)',
    'settings.calorieTarget': 'Daily Calorie Target',
    'settings.macroRatios': 'Macro Ratios',
    'settings.protein': 'Protein',
    'settings.carbs': 'Carbs',
    'settings.fats': 'Fats',
    'settings.waterGoal': 'Daily Water Goal (liters)',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Theme and colors',
    'settings.darkMode': 'Dark Mode',
    'settings.darkMode.desc': 'Switch between light and dark themes',
    'settings.account': 'Account & Data',
    'settings.account.desc': 'Manage profile and data',
    'settings.editProfile': 'Edit Profile',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.save': 'Save',
    'settings.resetProgress': 'Reset Progress',
    'settings.resetProgress.desc': 'Clear all logs and data',
    'settings.logout': 'Logout',
    'settings.logout.desc': 'Sign out of your account',
    'settings.confirmReset': 'Confirm Reset',
    'settings.confirmReset.desc': 'This will permanently delete all your data. This action cannot be undone.',
    'settings.confirm': 'Confirm',
    'settings.cancel': 'Cancel',
    'settings.confirmLogout': 'Confirm Logout',
    'settings.confirmLogout.desc': 'Are you sure you want to log out?',
    'settings.light': 'Light',
    'settings.dark': 'Dark',

    // AI Trainer Section
    'aiTrainer.badge': "AI Coach",
    'aiTrainer.title': "AI Coach Control",
    'aiTrainer.subtitle': "Monitor compliance, streaks, and adjust habits.",
    'aiTrainer.days.mon': "Mon",
    'aiTrainer.days.tue': "Tue",
    'aiTrainer.days.wed': "Wed",
    'aiTrainer.days.thu': "Thu",
    'aiTrainer.days.fri': "Fri",
    'aiTrainer.days.sat': "Sat",
    'aiTrainer.days.sun': "Sun",
    'aiTrainer.stats.weeklyScore': "Weekly compliance score",
    'aiTrainer.stats.loggingStreak': "Logging streak (days)",
    'aiTrainer.stats.activeWarnings': "Active warnings",
    'aiTrainer.stats.dismissed': "dismissed",
    'aiTrainer.stats.noDismissed': "None dismissed",
    'aiTrainer.chart.title': "Weekly compliance metric",
    'aiTrainer.chart.subtitle': "Daily adherence to nutrition and activity plan",
    'aiTrainer.warningsSection.title': "Alert notifications",
    'aiTrainer.warningsSection.subtitle': "Missed logs and diet deviations",
    'aiTrainer.warnings.missedThu.title': "Thursday meals not logged",
    'aiTrainer.warnings.missedThu.detail': "No meals were recorded for Thursday. This may lead to inaccurate weekly stats.",
    'aiTrainer.warnings.missedThu.tip': "Add missed meals from memory to restore tracking.",
    'aiTrainer.warnings.overCarbs.title': "Carbohydrate limit exceeded",
    'aiTrainer.warnings.overCarbs.detail': "Target carbohydrate amount was exceeded by 35g during dinner.",
    'aiTrainer.warnings.overCarbs.tip': "Slightly reduce carbs during tomorrow's breakfast and lunch.",
    'aiTrainer.warnings.lowSteps.title': "Low step count",
    'aiTrainer.warnings.lowSteps.detail': "Daily step goal fell short by 3,000 steps.",
    'aiTrainer.warnings.lowSteps.tip': "Schedule a 20-minute walk in the evening.",
    'aiTrainer.severity.high': "High",
    'aiTrainer.severity.medium': "Medium",
    'aiTrainer.severity.low': "Low",
    'aiTrainer.habitCorrection': "Habit adjustment:",
    'aiTrainer.dismiss': "Dismiss",
    'aiTrainer.allClear.title': "All warnings resolved",
    'aiTrainer.allClear.subtitle': "You are doing great! Keep up the good work.",
    'aiTrainer.habitsSection.title': "Habit list",
    'aiTrainer.habitsSection.subtitle': "Main actions for this week",
    'aiTrainer.habits.loggedMeals': "Log all meals",
    'aiTrainer.habits.hitProtein': "Hit protein target",
    'aiTrainer.habits.calorieRange': "Stay within calorie range",
    'aiTrainer.habits.completedSteps': "Complete step goal",
    'aiTrainer.habits.drankWater': "Drink daily water",
    'aiTrainer.recommendation.title': "Recommendation",
    'aiTrainer.recommendation.text.before': "Protein intake and water balance are steady. To maintain your streak, ",
    'aiTrainer.recommendation.text.highlight': "focus on logging your dinner on time.",
    'aiTrainer.recommendation.text.after': "",

    // Goals Section
    'goals.title': 'Goals & Achievements',
    'goals.subtitle': 'Set your goals, track your progress, and achieve results',
    'goals.addGoal': 'New Goal',
    'goals.activeGoals': 'Active Goals',
    'goals.completedGoals': 'Completed Goals',
    'goals.progress': 'Progress',
    'goals.targetDate': 'Deadline',
    'goals.daysLeft': 'days left',
    'goals.completed': 'Completed',
    'goals.category.weight': 'Weight',
    'goals.category.fitness': 'Fitness',
    'goals.category.nutrition': 'Nutrition',
    'goals.category.habit': 'Habit',
    'goals.newGoalModal.title': 'Add New Goal',
    'goals.newGoalModal.goalTitle': 'Goal Title',
    'goals.newGoalModal.category': 'Category',
    'goals.newGoalModal.targetValue': 'Target Value',
    'goals.newGoalModal.currentValue': 'Current Value',
    'goals.newGoalModal.unit': 'Unit of measurement (kg, days, etc.)',
    'goals.newGoalModal.deadline': 'Deadline',
    'goals.newGoalModal.save': 'Save',
    'goals.newGoalModal.cancel': 'Cancel',

    // Gym Finder Section
  'gymFinder.badge': 'Tashkent',
  'gymFinder.title': 'Gym Finder',
  'gymFinder.subtitle': 'Discover gyms and personal trainers near you in Tashkent.',
  'gymFinder.searchPlaceholder': 'Search by gym name or area...',
  'gymFinder.reviews': 'reviews',
  'gymFinder.facilities': 'Facilities',
  'gymFinder.trainers': 'Personal trainers',
  'gymFinder.notFound': 'No gyms found matching',
  'gymFinder.facility.freeWeights': 'Free weights',
  'gymFinder.facility.pool': 'Pool',
  'gymFinder.facility.cafe': 'Café',
  'gymFinder.facility.parking': 'Parking',
  'gymFinder.facility.crossfit': 'CrossFit zone',
  'gymFinder.facility.wifi': 'Free Wi-Fi',
  'gymFinder.facility.sauna': 'Sauna',
  'gymFinder.specialty.strength': 'Strength & conditioning',
  'gymFinder.specialty.yoga': 'Yoga & mobility',
  'gymFinder.specialty.crossfit': 'CrossFit & HIIT',
  'gymFinder.specialty.pilates': 'Pilates',
  'gymFinder.specialty.boxing': 'Boxing',
  'gymFinder.specialty.bodybuilding': 'Bodybuilding',
  'gymFinder.specialty.weightLoss': 'Weight loss',
  'gymFinder.specialty.functional': 'Functional training',
  'gymFinder.exp': 'yrs', 
  },
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('uz')

  useEffect(() => {
    const stored = localStorage.getItem('intizom-language') as Language | null
    if (stored && ['uz', 'ru', 'en'].includes(stored)) {
      setLanguageState(stored)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('intizom-language', lang)
  }

  const t = (key: string) => translations[language]?.[key] ?? translations.en[key] ?? key

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}