 'use client'

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'uz' | 'ru' | 'en'

type LanguageContextValue = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    // =========================
    // SIDEBAR
    // =========================
    'sidebar.dashboard': 'Bosh sahifa',
    'sidebar.steps': 'Qadamlar',
    'sidebar.gymFinder': 'Zallar',
    'sidebar.aiChat': 'AI Chat',
    'sidebar.recipes': 'Retseptlar',
    'sidebar.aiTrainer': 'AI Trener',
    'sidebar.insights': 'Tahlil va statistika',
    'sidebar.goals': 'Maqsadlar',
    'sidebar.settings': 'Sozlamalar',

    // =========================
    // DASHBOARD
    // =========================
    'dashboard.overview': 'Bosh sahifa',
    'dashboard.goals': 'Maqsadlar',
    'dashboard.insights': 'Tahlil',
    'dashboard.steps': 'Qadamlar',
    'dashboard.gymFinder': 'Zallar',
    'dashboard.recipes': 'Retseptlar',
    'dashboard.aiTrainer': 'AI Trener',
    'dashboard.adminPanel': 'Admin panel',
    'dashboard.settings': 'Sozlamalar',
    'dashboard.needHelp': 'Yordam kerakmi?',
    'dashboard.helpCenterText': "Ovqatlanish maqsadlaringizga erishish bo'yicha maslahatlar oling.",
    'dashboard.visitHelp': 'Yordam markazi',
    'dashboard.freePlan': 'Bepul tarif',
    'dashboard.openMenu': 'Menyuni ochish',
    'dashboard.closeMenu': 'Menyuni yopish',
    'dashboard.search': 'Qidirish',
    'dashboard.headerDate': '2026-yil 24-sentabr – 30-sentabr',

    'dashboard.salom': 'Salom',
    'dashboard.dailyOverview': 'Kunlik umumiy ko‘rinish',
    'dashboard.nutritionGoalsText': 'Ovqatlanish maqsadlaringiz bilan birga bo‘ling.',
    'dashboard.logMeal': 'Ovqat qo‘shish',

    'dashboard.todaysCalories': 'Bugungi kaloriyalar',
    'dashboard.dailyGoal': 'kunlik maqsad',
    'dashboard.kcalLeft': 'kkal qoldi',
    'dashboard.weeklyAverage': 'Haftalik o‘rtacha',
    'dashboard.kcalPerDay': 'kkal/kun',
    'dashboard.betterThanLastWeek': 'o‘tgan haftaga qaraganda yaxshiroq',
    'dashboard.carbs': 'Uglevodlar',
    'dashboard.protein': 'Protein',
    'dashboard.fat': 'Yog‘lar',
    'dashboard.macroBreakdown': 'Makronutrientlar tahlili',
    'dashboard.targetsProgress': 'Bugungi maqsadlaringizga nisbatan natijangiz',
    'dashboard.today': 'Bugun',

    'dashboard.scanWithCamera': 'Kamera bilan skanerlash',
    'dashboard.cameraIdentify': 'Kamera orqali aniqlash',
    'dashboard.cameraQuestion': 'Bugun nima yedingiz? Suratga oling va AI kaloriyalarni hisoblasin.',
    'dashboard.takePhoto': 'Rasmga olish va AI hisoblash',
    'dashboard.uploadPhoto': 'Rasm yuklash',
    'dashboard.dragAndDrop': 'yoki shu yerga tashlang',
    'dashboard.removeUploadedImage': 'Yuklangan rasmni o‘chirish',
    'dashboard.uploadedMealPreview': 'Yuklangan taom rasmi',

    'dashboard.fastingPlan': 'Ro‘za / Intervallik rejasi',
    'dashboard.stepByStepFasting': 'Bosqichma-bosqich reja',
    'dashboard.gentleRhythm': 'Bugun uchun mos 14:10 ritm.',
    'dashboard.eatingWindow': 'Ovqatlanish oynasi',
    'dashboard.fastingActive': 'Interval aktiv',
    'dashboard.startFast': 'Intervalni boshlash',
    'dashboard.completed': 'Bajarildi',
    'dashboard.smallHabits': 'Kichik odatlar, barqaror natija',
    'dashboard.fastingDesc': 'Odatlaringizni bajarish muntazam ovqatlanish tartibini yaratishga va kaloriyalarni to‘g‘ri kuzatishga yordam beradi.',
    'dashboard.stepsDone': 'bajarildi',
    'dashboard.fastingGoal': 'vaqt maqsadi',
    'dashboard.todaysPlan': 'bugungi reja',
    'dashboard.on': 'Yoqilgan',
    'dashboard.ready': 'Tayyor',

    'dashboard.myMeals': 'Mening ovqatlarim',
    'dashboard.fuelYourDay': 'Kuningizni sifatli ovqatlar bilan boyiting',
    'dashboard.visualLog': 'Bugun iste’mol qilgan barcha taomlaringiz ro‘yxati.',
    'dashboard.youHaveLogged': 'Bugun siz',
    'dashboard.mealsLoggedText': 'ta taom',
    'dashboard.calories': 'kaloriya',
    'dashboard.addAnotherMeal': 'Yana taom qo‘shish',
    'dashboard.moreOptions': 'Qo‘shimcha imkoniyatlar',

    'dashboard.foodVisionAI': 'Food Vision AI',
    'dashboard.cameraClose': 'Yopish',
    'dashboard.close': 'Yopish',
    'dashboard.analyzingMeal': 'Taom tahlil qilinmoqda...',
    'dashboard.cameraPrompt': 'Taom rasmini yuklang yoki nomini kiriting:',
    'dashboard.enterFoodName': 'Taom nomini kiriting...',
    'dashboard.scanButton': 'Tahlil qilish va saqlash',
    'dashboard.justNow': 'Hozirgina',

    'dashboard.mealType.meal': 'Taom',
    'dashboard.mealType.breakfast': 'Nonushta',
    'dashboard.mealType.lunch': 'Tushlik',
    'dashboard.mealType.snack': 'Yengil tamaddi',

    'dashboard.fasting.finishMeal': 'Oxirgi ovqatingizni soat 20:00 gacha tugating',
    'dashboard.fasting.windDown': 'Dam olishga tayyorlaning',
    'dashboard.fasting.drinkWater': 'Intervallik vaqt davomida suv iching',
    'dashboard.fasting.stayHydrated': 'Suv balansini saqlang',
    'dashboard.fasting.breakFast': 'Intervalni proteinli ovqat bilan yakunlang',
    'dashboard.fasting.fuelGently': 'Organizmni asta-sekin oziqlantiring',
    'dashboard.fasting.caffeine': 'Interval davomida shakarsiz kofein iste’mol qiling',
    'dashboard.fasting.keepSimple': 'Oddiy saqlang',

    'dashboard.weekdays.mon': 'Dush',
    'dashboard.weekdays.tue': 'Sesh',
    'dashboard.weekdays.wed': 'Chor',
    'dashboard.weekdays.thu': 'Pay',
    'dashboard.weekdays.fri': 'Jum',
    'dashboard.weekdays.sat': 'Shan',
    'dashboard.weekdays.sun': 'Yak',

    // =========================
    // SETTINGS
    // =========================
    'settings.title': 'Sozlamalar',
    'settings.language': 'Til',
    'settings.language.desc': "Ilova tilini o'zgartiring",
    'settings.notifications': 'Bildirishnomalar',
    'settings.notifications.desc': 'Eslatmalar va motivatsion xabarlar',
    'settings.motivational': 'Motivatsion bildirishnomalar',
    'settings.motivational.desc': "Nega kirmayapsiz? Dietani to'xtatmang!",
    'settings.mealReminders': 'Ovqat eslatmalari',
    'settings.breakfast': 'Nonushta',
    'settings.lunch': 'Tushlik',
    'settings.dinner': 'Kechki ovqat',
    'settings.waterReminders': 'Suv eslatmalari',
    'settings.waterReminders.desc': 'Kun davomida suv ichishni eslatish',
    'settings.goals': 'Maqsadlar va salomatlik',
    'settings.goals.desc': 'Vazn va kaloriya maqsadlari',
    'settings.currentWeight': 'Joriy vazn (kg)',
    'settings.targetWeight': 'Maqsad vazn (kg)',
    'settings.calorieTarget': 'Kunlik kaloriya maqsadi',
    'settings.macroRatios': 'Makro nisbatlar',
    'settings.protein': 'Protein',
    'settings.carbs': 'Uglevodlar',
    'settings.fats': 'Yog‘lar',
    'settings.waterGoal': 'Kunlik suv maqsadi (litr)',
    'settings.appearance': 'Tashqi ko‘rinish',
    'settings.appearance.desc': 'Mavzu va ranglar',
    'settings.darkMode': 'Qorong‘i rejim',
    'settings.darkMode.desc': 'Qorong‘i mavzuni yoqish',
    'settings.account': 'Hisob va ma’lumotlar',
    'settings.account.desc': 'Profil va ma’lumotlarni boshqarish',
    'settings.editProfile': 'Profilni tahrirlash',
    'settings.name': 'Ism',
    'settings.email': 'Email',
    'settings.save': 'Saqlash',
    'settings.resetProgress': 'Progressni tiklash',
    'settings.resetProgress.desc': 'Barcha ma’lumotlarni o‘chirish',
    'settings.logout': 'Chiqish',
    'settings.logout.desc': 'Hisobdan chiqish',
    'settings.confirmReset': 'Progressni tiklashni tasdiqlang',
    'settings.confirmReset.desc': 'Bu amal barcha ma’lumotlarni o‘chiradi va uni qaytarib bo‘lmaydi.',
    'settings.confirm': 'Tasdiqlash',
    'settings.cancel': 'Bekor qilish',
    'settings.confirmLogout': 'Chiqishni tasdiqlang',
    'settings.confirmLogout.desc': 'Hisobingizdan chiqishni xohlaysizmi?',
    'settings.light': 'Yorug‘',
    'settings.dark': 'Qorong‘i',

    // =========================
    // GOALS
    // =========================
    'goals.badge': 'Maqsadlar',
    'goals.title': 'Maqsadlar va Yutuqlar',
    'goals.subtitle': 'Maqsadingizni belgilang, progressni kuzating va yutuqlarga erishing',
    'goals.addGoal': 'Yangi maqsad',
    'goals.activeGoals': 'Faol maqsadlar',
    'goals.completedGoals': 'Bajarilgan maqsadlar',
    'goals.progress': 'Progress',
    'goals.targetDate': 'Muddat',
    'goals.daysLeft': 'kun qoldi',
    'goals.completed': 'Bajarildi',
    'goals.saved': 'Saqlandi',
    'goals.cancel': 'Bekor qilish',
    'goals.save': 'Saqlash',
    'goals.edit': 'Tahrirlash',
    'goals.targetWeightTracker': 'Maqsad vazn kuzatuvi',
    'goals.progressFrom': 'Progress:',
    'goals.to': 'dan',
    'goals.current': 'Joriy',
    'goals.goal': 'Maqsad',
    'goals.remaining': 'Qolgan',
    'goals.kgLost': 'kg yo‘qotildi',
    'goals.justStarted': 'Endi boshlandi',
    'goals.start': 'Boshlanish',
    'goals.currentWeightLabel': 'Joriy vazn (kg)',
    'goals.goalWeightLabel': 'Maqsad vazn (kg)',
    'goals.dailyMacroTargets': 'Kunlik makro maqsadlar',
    'goals.macroSubtitle': 'Kaloriya va makroelementlar maqsadlari',
    'goals.daily': 'Kunlik',
    'goals.dailyCalorieGoal': 'Kunlik kaloriya maqsadi',
    'goals.kcal': 'kkal',
    'goals.protein': 'Protein',
    'goals.carbs': 'Uglevodlar',
    'goals.fat': 'Yog‘',
    'goals.dailySteps': 'Kunlik qadamlar',
    'goals.stepCountGoal': 'Qadamlar maqsadi',
    'goals.stepsSuffix': 'qadam',
    'goals.todaySteps': 'bugun / maqsad:',
    'goals.waterIntake': 'Suv iste’moli',
    'goals.hydrationGoal': 'Kunlik suv maqsadi',
    'goals.literPerDay': 'litr/kun',
    'goals.todayWater': 'bugun / maqsad:',
    'goals.footerNote': 'Maqsadlaringizni muntazam yangilab turing.',
    'goals.saveChanges': 'O‘zgarishlarni saqlash',
    'goals.decrease': 'Kamaytirish',
    'goals.increase': 'Ko‘paytirish',
    'goals.category.weight': 'Vazn',
    'goals.category.fitness': 'Fitnes',
    'goals.category.nutrition': 'Oziqlanish',
    'goals.category.habit': 'Odat',
    'goals.newGoalModal.title': 'Yangi maqsad qo‘shish',
    'goals.newGoalModal.goalTitle': 'Maqsad nomi',
    'goals.newGoalModal.category': 'Kategoriya',
    'goals.newGoalModal.targetValue': 'Maqsad ko‘rsatkichi',
    'goals.newGoalModal.currentValue': 'Joriy ko‘rsatkich',
    'goals.newGoalModal.unit': 'O‘lchov birligi (kg, kun va h.k.)',
    'goals.newGoalModal.deadline': 'Oxirgi muddat',
    'goals.newGoalModal.save': 'Saqlash',
    'goals.newGoalModal.cancel': 'Bekor qilish',

    // =========================
    // GYM FINDER
    // =========================
    'gymFinder.badge': 'Toshkent',
    'gymFinder.title': 'Sport Zallari va Trenerlar',
    'gymFinder.subtitle': 'Toshkentdagi o‘zingizga yaqin sport zallari va shaxsiy murabbiylarni toping.',
    'gymFinder.searchPlaceholder': 'Zal nomi yoki tuman bo‘yicha qidiring...',
    'gymFinder.reviews': 'sharhlar',
    'gymFinder.facilities': 'Qulayliklar va imkoniyatlar',
    'gymFinder.trainers': 'Shaxsiy murabbiylar',
    'gymFinder.notFound': 'bo‘yicha hech qanday zal topilmadi.',
    'gymFinder.facility.freeWeights': 'Erkin vaznlar',
    'gymFinder.facility.pool': 'Basseyn',
    'gymFinder.facility.cafe': 'Kafe',
    'gymFinder.facility.parking': 'Avtoturargoh',
    'gymFinder.facility.crossfit': 'CrossFit zonasi',
    'gymFinder.facility.wifi': 'Bepul Wi-Fi',
    'gymFinder.facility.sauna': 'Sauna',
    'gymFinder.specialty.strength': 'Kuch va chidamlilik',
    'gymFinder.specialty.yoga': 'Yoga va harakatchanlik',
    'gymFinder.specialty.crossfit': 'CrossFit va HIIT',
    'gymFinder.specialty.pilates': 'Pilates',
    'gymFinder.specialty.boxing': 'Boks',
    'gymFinder.specialty.bodybuilding': 'Bodibilding',
    'gymFinder.specialty.weightLoss': 'Vazn tashlash',
    'gymFinder.specialty.functional': 'Funksional mashg‘ulotlar',
    'gymFinder.exp': 'yil',

    // =========================
    // STEPS
    // =========================
    'steps.badge': 'Pedometr',
    'steps.title': 'Qadamlar hisoblagichi',
    'steps.subtitle': 'Kundalik harakatingizni kuzating va faol bo‘ling.',
    'steps.of': 'dan',
    'steps.steps': 'qadam',
    'steps.kmWalked': 'km yurildi',
    'steps.activeKcal': 'faol kkal',
    'steps.activeMin': 'faol daqiqa',
    'steps.dailyGoal': 'kunlik maqsad',
    'steps.toGo': 'qadam qoldi',
    'steps.hourlyBreakdown': 'Soatlik ko‘rsatkich',
    'steps.byTimeOfDay': 'Kun davomida qadamlar',
    'steps.peakHour': 'Eng faol soat',
    'steps.todayActivity': 'Bugungi faoliyat',
    'steps.recordedMovements': 'Kun davomida qayd etilgan harakatlar',
    'steps.logActivity': 'Faoliyat qo‘shish (+500)',
    'steps.minute': 'daqiqa',
    'steps.activity.morningWalk': 'Ertalabki sayr',
    'steps.activity.lunchErrand': 'Tushlik paytidagi yurish',
    'steps.activity.eveningJog': 'Kechki yugurish',
    'steps.activity.manualWalk': 'Qo‘lda qo‘shilgan yurish',

    // =========================
    // RECIPES
    // =========================
    'recipes.badge': 'Sog‘lom retseptlar',
    'recipes.title': 'Retseptlar',
    'recipes.subtitle': 'To‘liq makro ma’lumotlari va tayyorlash bosqichlari bilan foydali taomlarni toping.',
    'recipes.favorites': 'sevimli',
    'recipes.searchPlaceholder': 'Retseptlarni qidiring...',
    'recipes.category.all': 'Barchasi',
    'recipes.category.lowCarb': 'Kam uglevodli',
    'recipes.category.highProtein': 'Yuqori protein',
    'recipes.category.uzbekFit': 'O‘zbek Fit taomlari',
    'recipes.category.quickSnacks': 'Tezkor tamaddilar',
    'recipes.min': 'daq',
    'recipes.servings': 'porsiya',
    'recipes.protein': 'protein',
    'recipes.carbs': 'uglevod',
    'recipes.fat': 'yog‘',
    'recipes.toggleFavorite': 'Sevimliga qo‘shish',
    'recipes.close': 'Yopish',
    'recipes.minutes': 'daqiqa',
    'recipes.serving': 'porsiya',
    'recipes.servingsPlural': 'porsiya',
    'recipes.instructions': 'Tayyorlash bosqichlari',
    'recipes.savedToFavorites': 'Sevimlilarga saqlandi',
    'recipes.addToFavorites': 'Sevimlilarga qo‘shish',
    'recipes.noResults': 'Retsept topilmadi. Boshqa qidiruv yoki kategoriyani sinab ko‘ring.',

    // Recipe names
    'recipes.recipe.grilledChicken.name': 'Grilda pishirilgan tovuqli salat',
    'recipes.recipe.beefShashlik.name': 'Mol go‘shti shashlik (Fit)',
    'recipes.recipe.greekYogurt.name': 'Yunon yogurti parfesi',
    'recipes.recipe.salmonAvocado.name': 'Losos va avokado bowl',
    'recipes.recipe.mungBean.name': 'Mosh sho‘rva',
    'recipes.recipe.proteinSmoothie.name': 'Proteinli smuzi',
    'recipes.recipe.turkeyWraps.name': 'Kurka go‘shtli salat wraplari',
    'recipes.recipe.eggAvocado.name': 'Tuxum va avokadoli tost (Fit)',

    // =========================
    // INSIGHTS
    // =========================
    'insights.badge': 'AI Smart Insights',
    'insights.title': 'Haftalik tahlil',
    'insights.subtitle': 'Progressingizni kuzating, odatlarni aniqlang va AI tavsiyalarini oling.',
    'insights.dateRange': '24-sentabr – 30-sentabr, 2026',

    'insights.avgCaloriesBurned': 'O‘rtacha yoqilgan kaloriyalar',
    'insights.avgCaloriesConsumed': 'O‘rtacha iste’mol qilingan kaloriyalar',
    'insights.totalSteps': 'Bu haftadagi jami qadamlar',
    'insights.hydrationScore': 'Suv balansi ko‘rsatkichi',
    'insights.kcalPerDay': 'kkal/kun',
    'insights.steps': 'qadam',
    'insights.upVsLastWeek': 'o‘tgan haftaga nisbatan oshgan',
    'insights.withinTarget': 'maqsad oralig‘ida',
    'insights.slightlyBelowGoal': 'maqsaddan biroz past',

    'insights.tabs.weekly': 'Haftalik progress',
    'insights.tabs.macros': 'Makronutrientlar',
    'insights.tabs.ai': 'AI tahlili',

    'insights.caloriesStepsProgress': 'Kaloriya va qadamlar progressi',
    'insights.burnedVsConsumed': 'Yoqilgan va iste’mol qilingan kaloriyalar',
    'insights.burned': 'Yoqilgan',
    'insights.consumed': 'Iste’mol qilingan',
    'insights.stepsTrend': 'Qadamlar dinamikasi',
    'insights.dailyStepsWeek': 'Hafta davomida kunlik qadamlar',
    'insights.peakBurnDay': 'Eng ko‘p kaloriya yoqilgan kun',
    'insights.peakStepDay': 'Eng ko‘p qadam bosilgan kun',

    'insights.macroDistribution': 'Makronutrientlar taqsimoti',
    'insights.macroBreakdown': 'Protein · Uglevod · Yog‘',
    'insights.dailyMacroBreakdown': 'Kunlik makro tahlili',
    'insights.gramsPerMacro': 'Hafta bo‘yicha makro ko‘rsatkichlari',
    'insights.total': 'Jami',
    'insights.percentage': 'Foiz',
    'insights.proteinRatio': 'Protein nisbati tavsiya etilgan 25% dan yuqori — mushaklarni saqlash uchun yaxshi.',

    'insights.strongHabit': 'Yaxshi odat',
    'insights.improve': 'Yaxshilash',
    'insights.pattern': 'Odat',
    'insights.aiInsight': 'AI tahlili',

    'insights.days.mon': 'Dush',
    'insights.days.tue': 'Sesh',
    'insights.days.wed': 'Chor',
    'insights.days.thu': 'Pay',
    'insights.days.fri': 'Jum',
    'insights.days.sat': 'Shan',
    'insights.days.sun': 'Yak',

    // AI insights
    'insights.ai.protein.title': 'Chorshanba kuni protein maqsadi bajarildi',
    'insights.ai.protein.detail': 'Siz 142g protein oldingiz — kunlik maqsadning 101%. Bu o‘tgan haftadagi eng barqaror kuningizga o‘xshaydi. Nonushtada proteinli mahsulotlarni saqlab qoling.',
    'insights.ai.protein.highlight': '142g · maqsadning 101%',

    'insights.ai.steps.title': 'Qadamlar soni oshmoqda',
    'insights.ai.steps.detail': 'Bu hafta kuniga o‘rtacha 9 743 qadam yurdingiz — o‘tgan haftaga nisbatan 12% ko‘p. Shanba kuni 12 400 qadam bilan eng yuqori natija qayd etildi.',
    'insights.ai.steps.highlight': 'O‘tgan haftaga nisbatan 12%',

    'insights.ai.hydration.title': 'Payshanba kuni suv iste’moli kamaydi',
    'insights.ai.hydration.detail': 'Payshanba kuni suv iste’moli maqsadning 64%igacha tushdi — aynan shu kuni kaloriyalar eng ko‘p bo‘lgan. Ovqat bilan birga bir stakan suv ichish bu farqni kamaytirishga yordam beradi.',
    'insights.ai.hydration.highlight': '64% — maqsaddan past',

    'insights.ai.evening.title': 'Kechki ovqat kaloriyalarni oshirmoqda',
    'insights.ai.evening.detail': 'Eng yuqori kaloriyali besh kuningizdan uchtasida kechki ovqat 21:00 dan keyin bo‘lgan. Oxirgi ovqatni ertaroq qilish 14:10 intervalingizga mos keladi.',
    'insights.ai.evening.highlight': '3 ta kechki ovqat',

    // =========================
    // AI TRAINER
    // =========================
    'aiTrainer.badge': 'Sun’iy intellekt murabbiyi',
    'aiTrainer.title': 'AI Murabbiy nazorati',
    'aiTrainer.subtitle': 'Riyoatni monitoring qilish, seriyalar va odatlarni to‘g‘rilash.',
    'aiTrainer.days.mon': 'Dush',
    'aiTrainer.days.tue': 'Sesh',
    'aiTrainer.days.wed': 'Chor',
    'aiTrainer.days.thu': 'Pay',
    'aiTrainer.days.fri': 'Jum',
    'aiTrainer.days.sat': 'Shan',
    'aiTrainer.days.sun': 'Yak',
    'aiTrainer.stats.weeklyScore': 'Haftalik rioya qilish bali',
    'aiTrainer.stats.loggingStreak': 'Yozib borish seriyasi (kun)',
    'aiTrainer.stats.activeWarnings': 'Faol ogohlantirishlar',
    'aiTrainer.stats.dismissed': 'yashirildi',
    'aiTrainer.stats.noDismissed': 'Yashirilganlar yo‘q',
    'aiTrainer.chart.title': 'Haftalik rioya ko‘rsatkichi',
    'aiTrainer.chart.subtitle': 'Oziqlanish va faollik rejasiga kunlik amal qilish',
    'aiTrainer.warningsSection.title': 'Ogohlantirish bildirishnomalari',
    'aiTrainer.warningsSection.subtitle': 'O‘tkazib yuborilgan qaydlar va diyetadan chetlashishlar',
    'aiTrainer.warnings.missedThu.title': 'Payshanba kuni ovqatlanish qayd etilmadi',
    'aiTrainer.warnings.missedThu.detail': 'Payshanba kuni uchun hech qanday ovqatlanish yozib borilmadi.',
    'aiTrainer.warnings.missedThu.tip': 'O‘tkazib yuborilgan ovqatlarni qo‘shing.',
    'aiTrainer.warnings.overCarbs.title': 'Uglevodlar me’yoridan oshdi',
    'aiTrainer.warnings.overCarbs.detail': 'Kechki ovqatda mo‘ljallangan uglevodlar miqdori 35g ga oshib ketdi.',
    'aiTrainer.warnings.overCarbs.tip': 'Ertangi nonushta va tushlikda uglevodlarni biroz kamaytiring.',
    'aiTrainer.warnings.lowSteps.title': 'Qadamlar soni kam',
    'aiTrainer.warnings.lowSteps.detail': 'Kunlik qadamlar maqsadi 3 000 qadamga kam bajarildi.',
    'aiTrainer.warnings.lowSteps.tip': 'Kechki payt 20 daqiqalik sayr qilishni rejalashtiring.',
    'aiTrainer.severity.high': 'Yuqori',
    'aiTrainer.severity.medium': 'O‘rta',
    'aiTrainer.severity.low': 'Past',
    'aiTrainer.habitCorrection': 'Odatni to‘g‘rilash:',
    'aiTrainer.dismiss': 'Yopish',
    'aiTrainer.allClear.title': 'Barcha ogohlantirishlar hal qilindi',
    'aiTrainer.allClear.subtitle': 'Siz ajoyib natija ko‘rsatmoqdasiz! Shunday davom eting.',
    'aiTrainer.habitsSection.title': 'Odatlar ro‘yxati',
    'aiTrainer.habitsSection.subtitle': 'Ushbu haftaning asosiy xatti-harakatlari',
    'aiTrainer.habits.loggedMeals': 'Barcha ovqatlarni yozish',
    'aiTrainer.habits.hitProtein': 'Protein me’yoriga yetish',
    'aiTrainer.habits.calorieRange': 'Kaloriya oralig‘ida bo‘lish',
    'aiTrainer.habits.completedSteps': 'Qadamlar maqsadini bajarish',
    'aiTrainer.habits.drankWater': 'Kunlik suvni ichish',
    'aiTrainer.recommendation.title': 'Tavsiya',
    'aiTrainer.recommendation.text.before': 'Protein iste’moli va suv balansi barqaror. Ketma-ketlikni saqlab qolish uchun ',
    'aiTrainer.recommendation.text.highlight': 'kechki ovqatni vaqtida qayd etishga ',
    'aiTrainer.recommendation.text.after': 'e’tibor bering.',

    // =========================
    // ADMIN
    // =========================
    'admin.restrictedAccess': 'Cheklangan kirish',
    'admin.adminPrefix': 'Admin:',
    'admin.executiveWorkspace': 'Boshqaruv ish maydoni',
    'admin.title': 'Admin panel',
    'admin.subtitle': 'Jonli foydalanuvchi faolligi va ovqatlanish tahlili.',
    'admin.close': 'Yopish',
    'admin.totalActiveUsers': 'Jami faol foydalanuvchilar',
    'admin.thisMonth': 'bu oy',
    'admin.todaysMealsLogged': 'Bugun qayd etilgan ovqatlar',
    'admin.liveCount': 'Jonli hisob',
    'admin.aiPhotoScans': 'AI orqali skanerlangan rasmlar',
    'admin.successful': 'muvaffaqiyatli',
    'admin.avgDailyCalories': 'O‘rtacha kunlik kaloriyalar',
    'admin.withinTarget': 'maqsad oralig‘ida',
    'admin.memberActivity': 'A’zolar faolligi',
    'admin.dailyMealLogging': 'Oxirgi hafta davomida kunlik ovqat qaydlari',
    'admin.liveActivityFeed': 'Jonli faollik lentasi',
    'admin.recentMemberEvents': 'So‘nggi foydalanuvchi hodisalari',
    'admin.live': 'Jonli',
    'admin.viewAllActivity': 'Barcha faollikni ko‘rish',
    'admin.quickControls': 'Tezkor boshqaruv',
    'admin.manageWorkspace': 'Ish maydoni amallarini boshqarish.',
    'admin.exportMemberReport': 'Foydalanuvchi hisobotini eksport qilish',
    'admin.manageMembers': 'Foydalanuvchilarni boshqarish',
    'admin.workspaceSettings': 'Ish maydoni sozlamalari',
    'admin.days.mon': 'Dush',
    'admin.days.tue': 'Sesh',
    'admin.days.wed': 'Chor',
    'admin.days.thu': 'Pay',
    'admin.days.fri': 'Jum',
    'admin.days.sat': 'Shan',
    'admin.days.sun': 'Yak',
    'admin.actions.breakfast': 'Nonushta qayd etdi',
    'admin.actions.aiPhoto': 'AI orqali ovqat rasmini tahlil qildi',
    'admin.actions.completedGoal': 'Kunlik maqsadni bajardi',
    'admin.actions.eveningMeal': 'Kechki ovqatni qayd etdi',
    'admin.times.2min': '2 daqiqa oldin',
    'admin.times.18min': '18 daqiqa oldin',
    'admin.times.42min': '42 daqiqa oldin',
    'admin.times.1hr': '1 soat oldin',
  },

  // ============================================================
  // RUSSIAN
  // ============================================================
  ru: {
    'sidebar.dashboard': 'Главная',
    'sidebar.steps': 'Шаги',
    'sidebar.gymFinder': 'Залы',
    'sidebar.aiChat': 'AI Чат',
    'sidebar.recipes': 'Рецепты',
    'sidebar.aiTrainer': 'AI Тренер',
    'sidebar.insights': 'Аналитика',
    'sidebar.goals': 'Цели',
    'sidebar.settings': 'Настройки',

    'dashboard.overview': 'Главная',
    'dashboard.goals': 'Цели',
    'dashboard.insights': 'Аналитика',
    'dashboard.steps': 'Шаги',
    'dashboard.gymFinder': 'Залы',
    'dashboard.recipes': 'Рецепты',
    'dashboard.aiTrainer': 'AI Тренер',
    'dashboard.adminPanel': 'Админ панель',
    'dashboard.settings': 'Настройки',
    'dashboard.needHelp': 'Нужна помощь?',
    'dashboard.helpCenterText': 'Получите советы по достижению целей в питании.',
    'dashboard.visitHelp': 'Центр помощи',
    'dashboard.freePlan': 'Бесплатный план',
    'dashboard.openMenu': 'Открыть меню',
    'dashboard.closeMenu': 'Закрыть меню',
    'dashboard.search': 'Поиск',
    'dashboard.headerDate': '24–30 сентября 2026',

    'dashboard.salom': 'Привет',
    'dashboard.dailyOverview': 'Ежедневный обзор',
    'dashboard.nutritionGoalsText': 'Следите за своими целями по питанию.',
    'dashboard.logMeal': 'Добавить блюдо',

    'dashboard.todaysCalories': 'Сегодняшние калории',
    'dashboard.dailyGoal': 'дневная цель',
    'dashboard.kcalLeft': 'ккал осталось',
    'dashboard.weeklyAverage': 'Среднее за неделю',
    'dashboard.kcalPerDay': 'ккал/день',
    'dashboard.betterThanLastWeek': 'лучше, чем на прошлой неделе',
    'dashboard.carbs': 'Углеводы',
    'dashboard.protein': 'Белки',
    'dashboard.fat': 'Жиры',
    'dashboard.macroBreakdown': 'Анализ макронутриентов',
    'dashboard.targetsProgress': 'Ваш прогресс по сравнению с целями на сегодня',
    'dashboard.today': 'Сегодня',

    'dashboard.scanWithCamera': 'Сканировать камерой',
    'dashboard.cameraIdentify': 'Определение через камеру',
    'dashboard.cameraQuestion': 'Что вы сегодня ели? Сделайте фото, и AI рассчитает калории.',
    'dashboard.takePhoto': 'Сделать фото и рассчитать',
    'dashboard.uploadPhoto': 'Загрузить фото',
    'dashboard.dragAndDrop': 'или перетащите сюда',
    'dashboard.removeUploadedImage': 'Удалить загруженное изображение',
    'dashboard.uploadedMealPreview': 'Предпросмотр блюда',

    'dashboard.fastingPlan': 'План голодания',
    'dashboard.stepByStepFasting': 'Пошаговый план',
    'dashboard.gentleRhythm': 'Удобный ритм 14:10 на сегодня.',
    'dashboard.eatingWindow': 'Окно приема пищи',
    'dashboard.fastingActive': 'Голодание активно',
    'dashboard.startFast': 'Начать голодание',
    'dashboard.completed': 'Выполнено',
    'dashboard.smallHabits': 'Маленькие привычки, стабильный результат',
    'dashboard.fastingDesc': 'Соблюдение режима помогает сформировать постоянный рацион и лучше контролировать калории.',
    'dashboard.stepsDone': 'выполнено',
    'dashboard.fastingGoal': 'цель',
    'dashboard.todaysPlan': 'план на сегодня',
    'dashboard.on': 'Включено',
    'dashboard.ready': 'Готово',

    'dashboard.myMeals': 'Мои блюда',
    'dashboard.fuelYourDay': 'Наполняйте день качественной едой',
    'dashboard.visualLog': 'Список всего, что вы съели сегодня.',
    'dashboard.youHaveLogged': 'Сегодня вы записали',
    'dashboard.mealsLoggedText': 'блюд',
    'dashboard.calories': 'калорий',
    'dashboard.addAnotherMeal': 'Добавить еще блюдо',
    'dashboard.moreOptions': 'Дополнительные действия',

    'dashboard.foodVisionAI': 'Food Vision AI',
    'dashboard.cameraClose': 'Закрыть',
    'dashboard.close': 'Закрыть',
    'dashboard.analyzingMeal': 'Анализируем блюдо...',
    'dashboard.cameraPrompt': 'Загрузите фото блюда или введите название:',
    'dashboard.enterFoodName': 'Введите название блюда...',
    'dashboard.scanButton': 'Анализировать и сохранить',
    'dashboard.justNow': 'Только что',

    'dashboard.mealType.meal': 'Блюдо',
    'dashboard.mealType.breakfast': 'Завтрак',
    'dashboard.mealType.lunch': 'Обед',
    'dashboard.mealType.snack': 'Перекус',

    'dashboard.fasting.finishMeal': 'Закончите последний прием пищи до 20:00',
    'dashboard.fasting.windDown': 'Подготовьтесь к отдыху',
    'dashboard.fasting.drinkWater': 'Пейте воду во время окна голодания',
    'dashboard.fasting.stayHydrated': 'Поддерживайте водный баланс',
    'dashboard.fasting.breakFast': 'Завершите голодание белковым приемом пищи',
    'dashboard.fasting.fuelGently': 'Начинайте питание постепенно',
    'dashboard.fasting.caffeine': 'Во время голодания пейте кофе без сахара',
    'dashboard.fasting.keepSimple': 'Сохраняйте простоту',

    'dashboard.weekdays.mon': 'Пн',
    'dashboard.weekdays.tue': 'Вт',
    'dashboard.weekdays.wed': 'Ср',
    'dashboard.weekdays.thu': 'Чт',
    'dashboard.weekdays.fri': 'Пт',
    'dashboard.weekdays.sat': 'Сб',
    'dashboard.weekdays.sun': 'Вс',

    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.language.desc': 'Изменить язык приложения',
    'settings.notifications': 'Уведомления',
    'settings.notifications.desc': 'Напоминания и мотивационные сообщения',
    'settings.motivational': 'Мотивационные уведомления',
    'settings.motivational.desc': 'Почему не заходите? Не прерывайте диету!',
    'settings.mealReminders': 'Напоминания о приемах пищи',
    'settings.breakfast': 'Завтрак',
    'settings.lunch': 'Обед',
    'settings.dinner': 'Ужин',
    'settings.waterReminders': 'Напоминания о воде',
    'settings.waterReminders.desc': 'Напоминания пить воду в течение дня',
    'settings.goals': 'Цели и здоровье',
    'settings.goals.desc': 'Цели по весу и калориям',
    'settings.currentWeight': 'Текущий вес (кг)',
    'settings.targetWeight': 'Целевой вес (кг)',
    'settings.calorieTarget': 'Дневная цель калорий',
    'settings.macroRatios': 'Соотношение макросов',
    'settings.protein': 'Белки',
    'settings.carbs': 'Углеводы',
    'settings.fats': 'Жиры',
    'settings.waterGoal': 'Дневная цель воды (литры)',
    'settings.appearance': 'Оформление',
    'settings.appearance.desc': 'Тема и цвета',
    'settings.darkMode': 'Темная тема',
    'settings.darkMode.desc': 'Включить темную тему',
    'settings.account': 'Аккаунт и данные',
    'settings.account.desc': 'Управление профилем и данными',
    'settings.editProfile': 'Редактировать профиль',
    'settings.name': 'Имя',
    'settings.email': 'Эл. почта',
    'settings.save': 'Сохранить',
    'settings.resetProgress': 'Сбросить прогресс',
    'settings.resetProgress.desc': 'Удалить все данные',
    'settings.logout': 'Выйти',
    'settings.logout.desc': 'Выйти из аккаунта',
    'settings.confirmReset': 'Подтвердите сброс',
    'settings.confirmReset.desc': 'Это действие удалит все данные и не может быть отменено.',
    'settings.confirm': 'Подтвердить',
    'settings.cancel': 'Отмена',
    'settings.confirmLogout': 'Подтвердите выход',
    'settings.confirmLogout.desc': 'Вы действительно хотите выйти?',
    'settings.light': 'Светлая',
    'settings.dark': 'Темная',

    'goals.badge': 'Цели',
    'goals.title': 'Цели и достижения',
    'goals.subtitle': 'Устанавливайте цели, отслеживайте прогресс и достигайте результатов',
    'goals.addGoal': 'Новая цель',
    'goals.activeGoals': 'Активные цели',
    'goals.completedGoals': 'Завершенные цели',
    'goals.progress': 'Прогресс',
    'goals.targetDate': 'Срок',
    'goals.daysLeft': 'дней осталось',
    'goals.completed': 'Завершено',
    'goals.saved': 'Сохранено',
    'goals.cancel': 'Отмена',
    'goals.save': 'Сохранить',
    'goals.edit': 'Редактировать',
    'goals.targetWeightTracker': 'Отслеживание целевого веса',
    'goals.progressFrom': 'Прогресс:',
    'goals.to': 'из',
    'goals.current': 'Текущий',
    'goals.goal': 'Цель',
    'goals.remaining': 'Осталось',
    'goals.kgLost': 'кг потеряно',
    'goals.justStarted': 'Только начато',
    'goals.start': 'Начало',
    'goals.currentWeightLabel': 'Текущий вес (кг)',
    'goals.goalWeightLabel': 'Целевой вес (кг)',
    'goals.dailyMacroTargets': 'Дневные цели макросов',
    'goals.macroSubtitle': 'Цели по калориям и макронутриентам',
    'goals.daily': 'Дневная',
    'goals.dailyCalorieGoal': 'Дневная цель калорий',
    'goals.kcal': 'ккал',
    'goals.protein': 'Белки',
    'goals.carbs': 'Углеводы',
    'goals.fat': 'Жиры',
    'goals.dailySteps': 'Дневные шаги',
    'goals.stepCountGoal': 'Цель по шагам',
    'goals.stepsSuffix': 'шагов',
    'goals.todaySteps': 'сегодня / цель:',
    'goals.waterIntake': 'Потребление воды',
    'goals.hydrationGoal': 'Дневная цель воды',
    'goals.literPerDay': 'л/день',
    'goals.todayWater': 'сегодня / цель:',
    'goals.footerNote': 'Регулярно обновляйте свои цели.',
    'goals.saveChanges': 'Сохранить изменения',
    'goals.decrease': 'Уменьшить',
    'goals.increase': 'Увеличить',
    'goals.category.weight': 'Вес',
    'goals.category.fitness': 'Фитнес',
    'goals.category.nutrition': 'Питание',
    'goals.category.habit': 'Привычка',
    'goals.newGoalModal.title': 'Добавить новую цель',
    'goals.newGoalModal.goalTitle': 'Название цели',
    'goals.newGoalModal.category': 'Категория',
    'goals.newGoalModal.targetValue': 'Целевой показатель',
    'goals.newGoalModal.currentValue': 'Текущий показатель',
    'goals.newGoalModal.unit': 'Единица измерения (кг, дней и т.д.)',
    'goals.newGoalModal.deadline': 'Крайний срок',
    'goals.newGoalModal.save': 'Сохранить',
    'goals.newGoalModal.cancel': 'Отмена',

    'gymFinder.badge': 'Ташкент',
    'gymFinder.title': 'Спортзалы и тренеры',
    'gymFinder.subtitle': 'Найдите ближайшие спортивные залы и персональных тренеров в Ташкенте.',
    'gymFinder.searchPlaceholder': 'Поиск по названию или району...',
    'gymFinder.reviews': 'отзывов',
    'gymFinder.facilities': 'Удобства и оснащение',
    'gymFinder.trainers': 'Персональные тренеры',
    'gymFinder.notFound': 'по запросу ничего не найдено.',
    'gymFinder.facility.freeWeights': 'Свободные веса',
    'gymFinder.facility.pool': 'Бассейн',
    'gymFinder.facility.cafe': 'Кафе',
    'gymFinder.facility.parking': 'Парковка',
    'gymFinder.facility.crossfit': 'Кроссфит зона',
    'gymFinder.facility.wifi': 'Бесплатный Wi-Fi',
    'gymFinder.facility.sauna': 'Сауна',
    'gymFinder.specialty.strength': 'Силовой тренинг',
    'gymFinder.specialty.yoga': 'Йога и гибкость',
    'gymFinder.specialty.crossfit': 'CrossFit и HIIT',
    'gymFinder.specialty.pilates': 'Пилатес',
    'gymFinder.specialty.boxing': 'Бокс',
    'gymFinder.specialty.bodybuilding': 'Бодибилдинг',
    'gymFinder.specialty.weightLoss': 'Похудение',
    'gymFinder.specialty.functional': 'Функциональный тренинг',
    'gymFinder.exp': 'лет',

    'steps.badge': 'Шагомер',
    'steps.title': 'Счетчик шагов',
    'steps.subtitle': 'Отслеживайте ежедневную активность и оставайтесь активными.',
    'steps.of': 'из',
    'steps.steps': 'шагов',
    'steps.kmWalked': 'км пройдено',
    'steps.activeKcal': 'активных ккал',
    'steps.activeMin': 'активных минут',
    'steps.dailyGoal': 'дневная цель',
    'steps.toGo': 'шагов осталось',
    'steps.hourlyBreakdown': 'Почасовая статистика',
    'steps.byTimeOfDay': 'Шаги по времени суток',
    'steps.peakHour': 'Самый активный час',
    'steps.todayActivity': 'Активность сегодня',
    'steps.recordedMovements': 'Записанные движения в течение дня',
    'steps.logActivity': 'Добавить активность (+500)',
    'steps.minute': 'мин',
    'steps.activity.morningWalk': 'Утренняя прогулка',
    'steps.activity.lunchErrand': 'Прогулка во время обеда',
    'steps.activity.eveningJog': 'Вечерняя пробежка',
    'steps.activity.manualWalk': 'Добавленная вручную прогулка',

    'recipes.badge': 'Полезные рецепты',
    'recipes.title': 'Рецепты',
    'recipes.subtitle': 'Находите полезные блюда с полным разбором макросов и инструкциями.',
    'recipes.favorites': 'избранных',
    'recipes.searchPlaceholder': 'Поиск рецептов...',
    'recipes.category.all': 'Все',
    'recipes.category.lowCarb': 'Низкоуглеводные',
    'recipes.category.highProtein': 'Высокобелковые',
    'recipes.category.uzbekFit': 'Узбекские Fit блюда',
    'recipes.category.quickSnacks': 'Быстрые перекусы',
    'recipes.min': 'мин',
    'recipes.servings': 'порций',
    'recipes.protein': 'белки',
    'recipes.carbs': 'углеводы',
    'recipes.fat': 'жиры',
    'recipes.toggleFavorite': 'Добавить в избранное',
    'recipes.close': 'Закрыть',
    'recipes.minutes': 'минут',
    'recipes.serving': 'порция',
    'recipes.servingsPlural': 'порций',
    'recipes.instructions': 'Инструкция',
    'recipes.savedToFavorites': 'Сохранено в избранное',
    'recipes.addToFavorites': 'Добавить в избранное',
    'recipes.noResults': 'Рецепты не найдены. Попробуйте другой поиск или категорию.',

    'recipes.recipe.grilledChicken.name': 'Салат с курицей на гриле',
    'recipes.recipe.beefShashlik.name': 'Говяжий шашлык (Fit)',
    'recipes.recipe.greekYogurt.name': 'Парфе из греческого йогурта',
    'recipes.recipe.salmonAvocado.name': 'Боул с лососем и авокадо',
    'recipes.recipe.mungBean.name': 'Суп из маша',
    'recipes.recipe.proteinSmoothie.name': 'Протеиновый смузи',
    'recipes.recipe.turkeyWraps.name': 'Роллы с индейкой и салатом',
    'recipes.recipe.eggAvocado.name': 'Тост с яйцом и авокадо (Fit)',

    'insights.badge': 'AI Smart Insights',
    'insights.title': 'Еженедельная аналитика',
    'insights.subtitle': 'Отслеживайте прогресс, замечайте закономерности и получайте рекомендации AI.',
    'insights.dateRange': '24–30 сентября 2026',
    'insights.avgCaloriesBurned': 'Среднее количество сожженных калорий',
    'insights.avgCaloriesConsumed': 'Среднее количество потребленных калорий',
    'insights.totalSteps': 'Всего шагов за неделю',
    'insights.hydrationScore': 'Показатель гидратации',
    'insights.kcalPerDay': 'ккал/день',
    'insights.steps': 'шагов',
    'insights.upVsLastWeek': 'выше прошлой недели',
    'insights.withinTarget': 'в пределах цели',
    'insights.slightlyBelowGoal': 'немного ниже цели',
    'insights.tabs.weekly': 'Недельный прогресс',
    'insights.tabs.macros': 'Макронутриенты',
    'insights.tabs.ai': 'AI аналитика',
    'insights.caloriesStepsProgress': 'Прогресс калорий и шагов',
    'insights.burnedVsConsumed': 'Сожженные и потребленные калории',
    'insights.burned': 'Сожжено',
    'insights.consumed': 'Потреблено',
    'insights.stepsTrend': 'Динамика шагов',
    'insights.dailyStepsWeek': 'Ежедневные шаги за неделю',
    'insights.peakBurnDay': 'День с максимальным расходом',
    'insights.peakStepDay': 'День с максимальным количеством шагов',
    'insights.macroDistribution': 'Распределение макронутриентов',
    'insights.macroBreakdown': 'Белки · Углеводы · Жиры',
    'insights.dailyMacroBreakdown': 'Дневной разбор макросов',
    'insights.gramsPerMacro': 'Граммы макросов за неделю',
    'insights.total': 'Всего',
    'insights.percentage': 'Процент',
    'insights.proteinRatio': 'Соотношение белка выше рекомендуемых 25% — хорошо для поддержания мышц.',
    'insights.strongHabit': 'Хорошая привычка',
    'insights.improve': 'Улучшить',
    'insights.pattern': 'Закономерность',
    'insights.aiInsight': 'AI аналитика',
    'insights.days.mon': 'Пн',
    'insights.days.tue': 'Вт',
    'insights.days.wed': 'Ср',
    'insights.days.thu': 'Чт',
    'insights.days.fri': 'Пт',
    'insights.days.sat': 'Сб',
    'insights.days.sun': 'Вс',
    'insights.ai.protein.title': 'Цель по белку выполнена в среду',
    'insights.ai.protein.detail': 'Вы получили 142 г белка — 101% дневной цели. Это похоже на ваш самый стабильный день прошлой недели.',
    'insights.ai.protein.highlight': '142 г · 101% цели',
    'insights.ai.steps.title': 'Количество шагов растет',
    'insights.ai.steps.detail': 'В среднем вы проходили 9 743 шага в день — на 12% больше прошлой недели. В субботу был пик — 12 400 шагов.',
    'insights.ai.steps.highlight': '12% против прошлой недели',
    'insights.ai.hydration.title': 'В четверг снизилось потребление воды',
    'insights.ai.hydration.detail': 'Потребление воды упало до 64% от цели в четверг — в тот же день было больше всего калорий.',
    'insights.ai.hydration.highlight': '64% — ниже цели',
    'insights.ai.evening.title': 'Поздние ужины повышают калорийность',
    'insights.ai.evening.detail': 'Три из пяти самых калорийных дней имели ужин после 21:00. Более ранний последний прием пищи лучше соответствует окну 14:10.',
    'insights.ai.evening.highlight': '3 поздних ужина',

    'aiTrainer.badge': 'ИИ Тренер',
    'aiTrainer.title': 'Контроль ИИ Тренера',
    'aiTrainer.subtitle': 'Мониторинг соблюдения, серии и исправление привычек.',
    'aiTrainer.days.mon': 'Пн',
    'aiTrainer.days.tue': 'Вт',
    'aiTrainer.days.wed': 'Ср',
    'aiTrainer.days.thu': 'Чт',
    'aiTrainer.days.fri': 'Пт',
    'aiTrainer.days.sat': 'Сб',
    'aiTrainer.days.sun': 'Вс',
    'aiTrainer.stats.weeklyScore': 'Еженедельный балл соблюдения',
    'aiTrainer.stats.loggingStreak': 'Серия записей (дней)',
    'aiTrainer.stats.activeWarnings': 'Активные предупреждения',
    'aiTrainer.stats.dismissed': 'скрыто',
    'aiTrainer.stats.noDismissed': 'Скрытых нет',
    'aiTrainer.chart.title': 'Показатель еженедельного соблюдения',
    'aiTrainer.chart.subtitle': 'Ежедневное следование плану питания и активности',
    'aiTrainer.warningsSection.title': 'Уведомления и предупреждения',
    'aiTrainer.warningsSection.subtitle': 'Пропущенные записи и отклонения от диеты',
    'aiTrainer.warnings.missedThu.title': 'Питание в четверг не записано',
    'aiTrainer.warnings.missedThu.detail': 'За четверг не было внесено ни одного приема пищи.',
    'aiTrainer.warnings.missedThu.tip': 'Добавьте пропущенные приемы пищи.',
    'aiTrainer.warnings.overCarbs.title': 'Превышение нормы углеводов',
    'aiTrainer.warnings.overCarbs.detail': 'Количество углеводов во время ужина превысило норму на 35г.',
    'aiTrainer.warnings.overCarbs.tip': 'Немного сократите углеводы во время завтрака и обеда завтра.',
    'aiTrainer.warnings.lowSteps.title': 'Низкая активность (шаги)',
    'aiTrainer.warnings.lowSteps.detail': 'Дневная цель по шагам не дотянута на 3 000 шагов.',
    'aiTrainer.warnings.lowSteps.tip': 'Запланируйте 20-минутную вечернюю прогулку.',
    'aiTrainer.severity.high': 'Высокий',
    'aiTrainer.severity.medium': 'Средний',
    'aiTrainer.severity.low': 'Низкий',
    'aiTrainer.habitCorrection': 'Коррекция привычки:',
    'aiTrainer.dismiss': 'Закрыть',
    'aiTrainer.allClear.title': 'Все предупреждения устранены',
    'aiTrainer.allClear.subtitle': 'Отличный результат! Продолжайте в том же духе.',
    'aiTrainer.habitsSection.title': 'Список привычек',
    'aiTrainer.habitsSection.subtitle': 'Основные действия на этой неделе',
    'aiTrainer.habits.loggedMeals': 'Записывать все приемы пищи',
    'aiTrainer.habits.hitProtein': 'Выполнять норму белка',
    'aiTrainer.habits.calorieRange': 'Оставаться в пределах калорий',
    'aiTrainer.habits.completedSteps': 'Выполнить цель по шагам',
    'aiTrainer.habits.drankWater': 'Выпивать дневную норму воды',
    'aiTrainer.recommendation.title': 'Рекомендация',
    'aiTrainer.recommendation.text.before': 'Потребление белка и водный баланс стабильны. Чтобы сохранить серию, ',
    'aiTrainer.recommendation.text.highlight': 'уделите внимание своевременной записи ужина.',
    'aiTrainer.recommendation.text.after': '',

    'admin.restrictedAccess': 'Ограниченный доступ',
    'admin.adminPrefix': 'Админ:',
    'admin.executiveWorkspace': 'Рабочее пространство руководителя',
    'admin.title': 'Админ панель',
    'admin.subtitle': 'Активность пользователей и аналитика питания в реальном времени.',
    'admin.close': 'Закрыть',
    'admin.totalActiveUsers': 'Всего активных пользователей',
    'admin.thisMonth': 'в этом месяце',
    'admin.todaysMealsLogged': 'Блюд записано сегодня',
    'admin.liveCount': 'В реальном времени',
    'admin.aiPhotoScans': 'AI сканирований фото',
    'admin.successful': 'успешно',
    'admin.avgDailyCalories': 'Средние дневные калории',
    'admin.withinTarget': 'в пределах цели',
    'admin.memberActivity': 'Активность участников',
    'admin.dailyMealLogging': 'Ежедневные записи питания за последнюю неделю',
    'admin.liveActivityFeed': 'Лента активности',
    'admin.recentMemberEvents': 'Последние события пользователей',
    'admin.live': 'Онлайн',
    'admin.viewAllActivity': 'Посмотреть всю активность',
    'admin.quickControls': 'Быстрые настройки',
    'admin.manageWorkspace': 'Управление рабочим пространством.',
    'admin.exportMemberReport': 'Экспорт отчета пользователя',
    'admin.manageMembers': 'Управление пользователями',
    'admin.workspaceSettings': 'Настройки рабочего пространства',
    'admin.days.mon': 'Пн',
    'admin.days.tue': 'Вт',
    'admin.days.wed': 'Ср',
    'admin.days.thu': 'Чт',
    'admin.days.fri': 'Пт',
    'admin.days.sat': 'Сб',
    'admin.days.sun': 'Вс',
    'admin.actions.breakfast': 'Записал завтрак',
    'admin.actions.aiPhoto': 'Проанализировал фото еды через AI',
    'admin.actions.completedGoal': 'Выполнил дневную цель',
    'admin.actions.eveningMeal': 'Записал вечерний прием пищи',
    'admin.times.2min': '2 мин назад',
    'admin.times.18min': '18 мин назад',
    'admin.times.42min': '42 мин назад',
    'admin.times.1hr': '1 час назад',
  },

  // ============================================================
  // ENGLISH
  // ============================================================
  en: {
    'sidebar.dashboard': 'Dashboard',
    'sidebar.steps': 'Steps',
    'sidebar.gymFinder': 'Gym Finder',
    'sidebar.aiChat': 'AI Chat',
    'sidebar.recipes': 'Recipes',
    'sidebar.aiTrainer': 'AI Trainer',
    'sidebar.insights': 'Insights',
    'sidebar.goals': 'Goals',
    'sidebar.settings': 'Settings',

    'dashboard.overview': 'Overview',
    'dashboard.goals': 'Goals',
    'dashboard.insights': 'Insights',
    'dashboard.steps': 'Step Counter',
    'dashboard.gymFinder': 'Gym Finder',
    'dashboard.recipes': 'Recipes',
    'dashboard.aiTrainer': 'AI Trainer',
    'dashboard.adminPanel': 'Admin panel',
    'dashboard.settings': 'Settings',
    'dashboard.needHelp': 'Need a hand?',
    'dashboard.helpCenterText': 'Get tips for reaching your nutrition goals.',
    'dashboard.visitHelp': 'Visit help center',
    'dashboard.freePlan': 'Free plan',
    'dashboard.openMenu': 'Open menu',
    'dashboard.closeMenu': 'Close menu',
    'dashboard.search': 'Search',
    'dashboard.headerDate': 'September 24–30, 2026',

    'dashboard.salom': 'Hello',
    'dashboard.dailyOverview': 'Your daily overview',
    'dashboard.nutritionGoalsText': 'Stay on track with your nutrition goals.',
    'dashboard.logMeal': 'Log a meal',

    'dashboard.todaysCalories': "Today's calories",
    'dashboard.dailyGoal': 'daily goal',
    'dashboard.kcalLeft': 'kcal left',
    'dashboard.weeklyAverage': 'Weekly average',
    'dashboard.kcalPerDay': 'kcal/day',
    'dashboard.betterThanLastWeek': 'better than last week',
    'dashboard.carbs': 'Carbs',
    'dashboard.protein': 'Protein',
    'dashboard.fat': 'Fat',
    'dashboard.macroBreakdown': 'Macro breakdown',
    'dashboard.targetsProgress': "Your progress against today's targets",
    'dashboard.today': 'Today',

    'dashboard.scanWithCamera': 'Scan with camera',
    'dashboard.cameraIdentify': 'Identify via camera',
    'dashboard.cameraQuestion': 'What did you eat today? Take a photo and let AI compute calories.',
    'dashboard.takePhoto': 'Take photo & AI compute',
    'dashboard.uploadPhoto': 'Upload a photo',
    'dashboard.dragAndDrop': 'or drag and drop here',
    'dashboard.removeUploadedImage': 'Remove uploaded image',
    'dashboard.uploadedMealPreview': 'Uploaded meal preview',

    'dashboard.fastingPlan': 'Fasting plan',
    'dashboard.stepByStepFasting': 'Step-by-step fasting',
    'dashboard.gentleRhythm': 'A gentle 14:10 rhythm for today.',
    'dashboard.eatingWindow': 'Eating window',
    'dashboard.fastingActive': 'Fasting active',
    'dashboard.startFast': 'Start fast',
    'dashboard.completed': 'Completed',
    'dashboard.smallHabits': 'Small habits, steady progress',
    'dashboard.fastingDesc': 'Completing your routine helps create a consistent eating pattern and makes your calorie trend easier to understand.',
    'dashboard.stepsDone': 'steps done',
    'dashboard.fastingGoal': 'fasting goal',
    'dashboard.todaysPlan': "today's plan",
    'dashboard.on': 'On',
    'dashboard.ready': 'Ready',

    'dashboard.myMeals': 'My meals',
    'dashboard.fuelYourDay': 'Fuel your day, one plate at a time',
    'dashboard.visualLog': "A visual log of everything you've enjoyed today.",
    'dashboard.youHaveLogged': "You've logged",
    'dashboard.mealsLoggedText': 'meals',
    'dashboard.calories': 'calories',
    'dashboard.addAnotherMeal': 'Add another meal',
    'dashboard.moreOptions': 'More options',

    'dashboard.foodVisionAI': 'Food Vision AI',
    'dashboard.cameraClose': 'Close',
    'dashboard.close': 'Close',
    'dashboard.analyzingMeal': 'Analyzing meal...',
    'dashboard.cameraPrompt': 'Upload a photo or enter meal name:',
    'dashboard.enterFoodName': 'Enter food name...',
    'dashboard.scanButton': 'Analyze & Save',
    'dashboard.justNow': 'Just now',

    'dashboard.mealType.meal': 'Meal',
    'dashboard.mealType.breakfast': 'Breakfast',
    'dashboard.mealType.lunch': 'Lunch',
    'dashboard.mealType.snack': 'Snack',

    'dashboard.fasting.finishMeal': 'Finish your last meal by 8:00 PM',
    'dashboard.fasting.windDown': 'Wind down',
    'dashboard.fasting.drinkWater': 'Drink water during the fasting window',
    'dashboard.fasting.stayHydrated': 'Stay hydrated',
    'dashboard.fasting.breakFast': 'Break your fast with a protein-rich meal',
    'dashboard.fasting.fuelGently': 'Fuel gently',
    'dashboard.fasting.caffeine': 'Keep caffeine unsweetened while fasting',
    'dashboard.fasting.keepSimple': 'Keep it simple',

    'dashboard.weekdays.mon': 'Mon',
    'dashboard.weekdays.tue': 'Tue',
    'dashboard.weekdays.wed': 'Wed',
    'dashboard.weekdays.thu': 'Thu',
    'dashboard.weekdays.fri': 'Fri',
    'dashboard.weekdays.sat': 'Sat',
    'dashboard.weekdays.sun': 'Sun',

    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.language.desc': 'Change the app language',
    'settings.notifications': 'Notifications',
    'settings.notifications.desc': 'Reminders and motivational messages',
    'settings.motivational': 'Motivational Notifications',
    'settings.motivational.desc': "Why haven't you logged in today? Don't break your diet streak!",
    'settings.mealReminders': 'Meal Reminders',
    'settings.breakfast': 'Breakfast',
    'settings.lunch': 'Lunch',
    'settings.dinner': 'Dinner',
    'settings.waterReminders': 'Water Reminders',
    'settings.waterReminders.desc': 'Stay hydrated with water tracking reminders',
    'settings.goals': 'Goals & Health Profile',
    'settings.goals.desc': 'Weight and calorie targets',
    'settings.currentWeight': 'Current Weight (kg)',
    'settings.targetWeight': 'Target Weight (kg)',
    'settings.calorieTarget': 'Daily Calorie Target',
    'settings.macroRatios': 'Macro Ratios',
    'settings.protein': 'Protein',
    'settings.carbs': 'Carbs',
    'settings.fats': 'Fats',
    'settings.waterGoal': 'Daily Water Goal (liters)',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Theme and colors',
    'settings.darkMode': 'Dark Mode',
    'settings.darkMode.desc': 'Switch between light and dark themes',
    'settings.account': 'Account & Data',
    'settings.account.desc': 'Manage profile and data',
    'settings.editProfile': 'Edit Profile',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.save': 'Save',
    'settings.resetProgress': 'Reset Progress',
    'settings.resetProgress.desc': 'Clear all logs and data',
    'settings.logout': 'Logout',
    'settings.logout.desc': 'Sign out of your account',
    'settings.confirmReset': 'Confirm Reset',
    'settings.confirmReset.desc': 'This will permanently delete all your data. This action cannot be undone.',
    'settings.confirm': 'Confirm',
    'settings.cancel': 'Cancel',
    'settings.confirmLogout': 'Confirm Logout',
    'settings.confirmLogout.desc': 'Are you sure you want to log out?',
    'settings.light': 'Light',
    'settings.dark': 'Dark',

    'goals.badge': 'Goals',
    'goals.title': 'Goals & Achievements',
    'goals.subtitle': 'Set your goals, track your progress, and achieve results',
    'goals.addGoal': 'New Goal',
    'goals.activeGoals': 'Active Goals',
    'goals.completedGoals': 'Completed Goals',
    'goals.progress': 'Progress',
    'goals.targetDate': 'Deadline',
    'goals.daysLeft': 'days left',
    'goals.completed': 'Completed',
    'goals.saved': 'Saved',
    'goals.cancel': 'Cancel',
    'goals.save': 'Save',
    'goals.edit': 'Edit',
    'goals.targetWeightTracker': 'Target weight tracker',
    'goals.progressFrom': 'Progress:',
    'goals.to': 'of',
    'goals.current': 'Current',
    'goals.goal': 'Goal',
    'goals.remaining': 'Remaining',
    'goals.kgLost': 'kg lost',
    'goals.justStarted': 'Just started',
    'goals.start': 'Start',
    'goals.currentWeightLabel': 'Current weight (kg)',
    'goals.goalWeightLabel': 'Goal weight (kg)',
    'goals.dailyMacroTargets': 'Daily macro targets',
    'goals.macroSubtitle': 'Calorie and macronutrient targets',
    'goals.daily': 'Daily',
    'goals.dailyCalorieGoal': 'Daily calorie goal',
    'goals.kcal': 'kcal',
    'goals.protein': 'Protein',
    'goals.carbs': 'Carbs',
    'goals.fat': 'Fat',
    'goals.dailySteps': 'Daily steps',
    'goals.stepCountGoal': 'Step count goal',
    'goals.stepsSuffix': 'steps',
    'goals.todaySteps': 'today / goal:',
    'goals.waterIntake': 'Water intake',
    'goals.hydrationGoal': 'Daily hydration goal',
    'goals.literPerDay': 'L/day',
    'goals.todayWater': 'today / goal:',
    'goals.footerNote': 'Keep your goals updated regularly.',
    'goals.saveChanges': 'Save changes',
    'goals.decrease': 'Decrease',
    'goals.increase': 'Increase',
    'goals.category.weight': 'Weight',
    'goals.category.fitness': 'Fitness',
    'goals.category.nutrition': 'Nutrition',
    'goals.category.habit': 'Habit',
    'goals.newGoalModal.title': 'Add New Goal',
    'goals.newGoalModal.goalTitle': 'Goal Title',
    'goals.newGoalModal.category': 'Category',
    'goals.newGoalModal.targetValue': 'Target Value',
    'goals.newGoalModal.currentValue': 'Current Value',
    'goals.newGoalModal.unit': 'Unit of measurement (kg, days, etc.)',
    'goals.newGoalModal.deadline': 'Deadline',
    'goals.newGoalModal.save': 'Save',
    'goals.newGoalModal.cancel': 'Cancel',

    'gymFinder.badge': 'Tashkent',
    'gymFinder.title': 'Gym Finder',
    'gymFinder.subtitle': 'Discover gyms and personal trainers near you in Tashkent.',
    'gymFinder.searchPlaceholder': 'Search by gym name or area...',
    'gymFinder.reviews': 'reviews',
    'gymFinder.facilities': 'Facilities',
    'gymFinder.trainers': 'Personal trainers',
    'gymFinder.notFound': 'No gyms found matching',
    'gymFinder.facility.freeWeights': 'Free weights',
    'gymFinder.facility.pool': 'Pool',
    'gymFinder.facility.cafe': 'Café',
    'gymFinder.facility.parking': 'Parking',
    'gymFinder.facility.crossfit': 'CrossFit zone',
    'gymFinder.facility.wifi': 'Free Wi-Fi',
    'gymFinder.facility.sauna': 'Sauna',
    'gymFinder.specialty.strength': 'Strength & conditioning',
    'gymFinder.specialty.yoga': 'Yoga & mobility',
    'gymFinder.specialty.crossfit': 'CrossFit & HIIT',
    'gymFinder.specialty.pilates': 'Pilates',
    'gymFinder.specialty.boxing': 'Boxing',
    'gymFinder.specialty.bodybuilding': 'Bodybuilding',
    'gymFinder.specialty.weightLoss': 'Weight loss',
    'gymFinder.specialty.functional': 'Functional training',
    'gymFinder.exp': 'yrs',

    'steps.badge': 'Pedometer',
    'steps.title': 'Step Counter',
    'steps.subtitle': 'Track your daily movement and stay active.',
    'steps.of': 'of',
    'steps.steps': 'steps',
    'steps.kmWalked': 'km walked',
    'steps.activeKcal': 'active kcal',
    'steps.activeMin': 'active min',
    'steps.dailyGoal': 'of your daily goal',
    'steps.toGo': 'steps to go',
    'steps.hourlyBreakdown': 'Hourly breakdown',
    'steps.byTimeOfDay': 'Steps by time of day',
    'steps.peakHour': 'Peak hour',
    'steps.todayActivity': "Today's activity log",
    'steps.recordedMovements': 'Recorded movements throughout the day',
    'steps.logActivity': 'Log activity (+500)',
    'steps.minute': 'min',
    'steps.activity.morningWalk': 'Morning walk',
    'steps.activity.lunchErrand': 'Lunch errand',
    'steps.activity.eveningJog': 'Evening jog',
    'steps.activity.manualWalk': 'Manual walk step',

    'recipes.badge': 'Healthy recipes',
    'recipes.title': 'Recipes',
    'recipes.subtitle': 'Find nutritious meals with full macro breakdowns and instructions.',
    'recipes.favorites': 'favorites',
    'recipes.searchPlaceholder': 'Search recipes...',
    'recipes.category.all': 'All',
    'recipes.category.lowCarb': 'Low Carb',
    'recipes.category.highProtein': 'High Protein',
    'recipes.category.uzbekFit': 'Uzbek Fit Meals',
    'recipes.category.quickSnacks': 'Quick Snacks',
    'recipes.min': 'min',
    'recipes.servings': 'servings',
    'recipes.protein': 'protein',
    'recipes.carbs': 'carbs',
    'recipes.fat': 'fat',
    'recipes.toggleFavorite': 'Toggle favorite',
    'recipes.close': 'Close',
    'recipes.minutes': 'minutes',
    'recipes.serving': 'serving',
    'recipes.servingsPlural': 'servings',
    'recipes.instructions': 'Instructions',
    'recipes.savedToFavorites': 'Saved to favorites',
    'recipes.addToFavorites': 'Add to favorites',
    'recipes.noResults': 'No recipes found. Try a different search or category.',

    'recipes.recipe.grilledChicken.name': 'Grilled Chicken Salad',
    'recipes.recipe.beefShashlik.name': 'Beef Shashlik (Fit)',
    'recipes.recipe.greekYogurt.name': 'Greek Yogurt Parfait',
    'recipes.recipe.salmonAvocado.name': 'Salmon & Avocado Bowl',
    'recipes.recipe.mungBean.name': 'Mung Bean Soup (Mash)',
    'recipes.recipe.proteinSmoothie.name': 'Protein Smoothie',
    'recipes.recipe.turkeyWraps.name': 'Turkey Lettuce Wraps',
    'recipes.recipe.eggAvocado.name': 'Egg & Avocado Toast (Fit)',

    'insights.badge': 'AI Smart Insights',
    'insights.title': 'Weekly Insights',
    'insights.subtitle': 'Track your progress, spot patterns, and get AI-powered recommendations.',
    'insights.dateRange': 'Sep 24 – Sep 30, 2026',
    'insights.avgCaloriesBurned': 'Avg. calories burned',
    'insights.avgCaloriesConsumed': 'Avg. calories consumed',
    'insights.totalSteps': 'Total steps this week',
    'insights.hydrationScore': 'Water hydration score',
    'insights.kcalPerDay': 'kcal/day',
    'insights.steps': 'steps',
    'insights.upVsLastWeek': 'up vs last week',
    'insights.withinTarget': 'within target range',
    'insights.slightlyBelowGoal': 'slightly below goal',
    'insights.tabs.weekly': 'Weekly progress',
    'insights.tabs.macros': 'Macronutrients',
    'insights.tabs.ai': 'AI insights',
    'insights.caloriesStepsProgress': 'Calories & step progress',
    'insights.burnedVsConsumed': 'Burned vs consumed alongside daily steps',
    'insights.burned': 'Burned',
    'insights.consumed': 'Consumed',
    'insights.stepsTrend': 'Step trend',
    'insights.dailyStepsWeek': 'Daily steps over the week',
    'insights.peakBurnDay': 'Peak burn day',
    'insights.peakStepDay': 'Peak step day',
    'insights.macroDistribution': 'Macronutrient distribution',
    'insights.macroBreakdown': 'Protein · Carbs · Fat breakdown',
    'insights.dailyMacroBreakdown': 'Daily macro breakdown',
    'insights.gramsPerMacro': 'Grams per macro across the week',
    'insights.total': 'Total',
    'insights.percentage': 'Percentage',
    'insights.proteinRatio': 'Your protein ratio is above the recommended 25% — great for muscle maintenance.',
    'insights.strongHabit': 'Strong habit',
    'insights.improve': 'Improve',
    'insights.pattern': 'Pattern',
    'insights.aiInsight': 'AI insight',
    'insights.days.mon': 'Mon',
    'insights.days.tue': 'Tue',
    'insights.days.wed': 'Wed',
    'insights.days.thu': 'Thu',
    'insights.days.fri': 'Fri',
    'insights.days.sat': 'Sat',
    'insights.days.sun': 'Sun',
    'insights.ai.protein.title': 'Protein target nailed on Wednesday',
    'insights.ai.protein.detail': 'You hit 142g of protein — 101% of your daily goal. That mirrors your most consistent day last week.',
    'insights.ai.protein.highlight': '142g · 101% of goal',
    'insights.ai.steps.title': 'Step count trending up',
    'insights.ai.steps.detail': 'You averaged 9,743 steps/day this week, up 12% from last week. Saturday was your peak at 12,400 steps.',
    'insights.ai.steps.highlight': '12% vs last week',
    'insights.ai.hydration.title': 'Hydration dipped on Thursday',
    'insights.ai.hydration.detail': 'Water intake fell to 64% of your goal on Thursday — the same day you consumed the most calories.',
    'insights.ai.hydration.highlight': '64% — below target',
    'insights.ai.evening.title': 'Late dinners spiking calorie totals',
    'insights.ai.evening.detail': 'Three of your five highest-calorie days had dinners after 9 PM. Shifting your last meal earlier aligns with your 14:10 fasting window.',
    'insights.ai.evening.highlight': '3 late dinners logged',

    'aiTrainer.badge': 'AI Coach',
    'aiTrainer.title': 'AI Coach Control',
    'aiTrainer.subtitle': 'Monitor compliance, streaks, and adjust habits.',
    'aiTrainer.days.mon': 'Mon',
    'aiTrainer.days.tue': 'Tue',
    'aiTrainer.days.wed': 'Wed',
    'aiTrainer.days.thu': 'Thu',
    'aiTrainer.days.fri': 'Fri',
    'aiTrainer.days.sat': 'Sat',
    'aiTrainer.days.sun': 'Sun',
    'aiTrainer.stats.weeklyScore': 'Weekly compliance score',
    'aiTrainer.stats.loggingStreak': 'Logging streak (days)',
    'aiTrainer.stats.activeWarnings': 'Active warnings',
    'aiTrainer.stats.dismissed': 'dismissed',
    'aiTrainer.stats.noDismissed': 'None dismissed',
    'aiTrainer.chart.title': 'Weekly compliance metric',
    'aiTrainer.chart.subtitle': 'Daily adherence to nutrition and activity plan',
    'aiTrainer.warningsSection.title': 'Alert notifications',
    'aiTrainer.warningsSection.subtitle': 'Missed logs and diet deviations',
    'aiTrainer.warnings.missedThu.title': 'Thursday meals not logged',
    'aiTrainer.warnings.missedThu.detail': 'No meals were recorded for Thursday.',
    'aiTrainer.warnings.missedThu.tip': 'Add missed meals from memory.',
    'aiTrainer.warnings.overCarbs.title': 'Carbohydrate limit exceeded',
    'aiTrainer.warnings.overCarbs.detail': 'Target carbohydrate amount was exceeded by 35g during dinner.',
    'aiTrainer.warnings.overCarbs.tip': "Slightly reduce carbs during tomorrow's breakfast and lunch.",
    'aiTrainer.warnings.lowSteps.title': 'Low step count',
    'aiTrainer.warnings.lowSteps.detail': 'Daily step goal fell short by 3,000 steps.',
    'aiTrainer.warnings.lowSteps.tip': 'Schedule a 20-minute walk in the evening.',
    'aiTrainer.severity.high': 'High',
    'aiTrainer.severity.medium': 'Medium',
    'aiTrainer.severity.low': 'Low',
    'aiTrainer.habitCorrection': 'Habit adjustment:',
    'aiTrainer.dismiss': 'Dismiss',
    'aiTrainer.allClear.title': 'All warnings resolved',
    'aiTrainer.allClear.subtitle': 'You are doing great! Keep up the good work.',
    'aiTrainer.habitsSection.title': 'Habit list',
    'aiTrainer.habitsSection.subtitle': 'Main actions for this week',
    'aiTrainer.habits.loggedMeals': 'Log all meals',
    'aiTrainer.habits.hitProtein': 'Hit protein target',
    'aiTrainer.habits.calorieRange': 'Stay within calorie range',
    'aiTrainer.habits.completedSteps': 'Complete step goal',
    'aiTrainer.habits.drankWater': 'Drink daily water',
    'aiTrainer.recommendation.title': 'Recommendation',
    'aiTrainer.recommendation.text.before': 'Protein intake and water balance are steady. To maintain your streak, ',
    'aiTrainer.recommendation.text.highlight': 'focus on logging your dinner on time.',
    'aiTrainer.recommendation.text.after': '',

    'admin.restrictedAccess': 'Restricted access',
    'admin.adminPrefix': 'Admin:',
    'admin.executiveWorkspace': 'Executive workspace',
    'admin.title': 'Admin panel',
    'admin.subtitle': 'Live member activity and nutrition intelligence.',
    'admin.close': 'Close',
    'admin.totalActiveUsers': 'Total active users',
    'admin.thisMonth': 'this month',
    'admin.todaysMealsLogged': "Today's meals logged",
    'admin.liveCount': 'Live count',
    'admin.aiPhotoScans': 'AI photo scans',
    'admin.successful': 'successful',
    'admin.avgDailyCalories': 'Avg. daily calories',
    'admin.withinTarget': 'Within target',
    'admin.memberActivity': 'Member activity',
    'admin.dailyMealLogging': 'Daily meal logging over the past week',
    'admin.liveActivityFeed': 'Live activity feed',
    'admin.recentMemberEvents': 'Recent member events',
    'admin.live': 'Live',
    'admin.viewAllActivity': 'View all activity',
    'admin.quickControls': 'Quick controls',
    'admin.manageWorkspace': 'Manage workspace operations.',
    'admin.exportMemberReport': 'Export member report',
    'admin.manageMembers': 'Manage members',
    'admin.workspaceSettings': 'Workspace settings',
    'admin.days.mon': 'Mon',
    'admin.days.tue': 'Tue',
    'admin.days.wed': 'Wed',
    'admin.days.thu': 'Thu',
    'admin.days.fri': 'Fri',
    'admin.days.sat': 'Sat',
    'admin.days.sun': 'Sun',
    'admin.actions.breakfast': 'Logged a breakfast',
    'admin.actions.aiPhoto': 'Analyzed food photo via AI',
    'admin.actions.completedGoal': 'Completed daily goal',
    'admin.actions.eveningMeal': 'Logged an evening meal',
    'admin.times.2min': '2 min ago',
    'admin.times.18min': '18 min ago',
    'admin.times.42min': '42 min ago',
    'admin.times.1hr': '1 hr ago',
  },
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('uz')

  useEffect(() => {
    const stored = localStorage.getItem('intizom-language') as Language | null

    if (stored && ['uz', 'ru', 'en'].includes(stored)) {
      setLanguageState(stored)
    }
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('intizom-language', lang)
  }

  const t = (key: string) => {
    return translations[language]?.[key] ?? translations.en[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)

  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }

  return ctx
}